---
config:
  class:
    hideEmptyMembersBox: true
  layout: dagre
  theme: neutral
---
classDiagram

class GWMethodologies:::forFixing {
  + gwCharacterisationReference : ReferenceType
  + trendAssessmentPerformed : YesNo
  + trendAssessmentMethodology : YesNo [0..1]
  + timeSeries : range [0..1]
  + statisticalElements : StatisticalElements [0..1]
  + additionalTrendAssessment : YesNo
  + trendReversalMethodology : YesNo
  + thresholdValueElementProtectionEcosystem : YesNo
  + transboundaryThresholdValues : YesNoNotApplicable
  
  «pending-discussion»
  + thresholdValueElementProtectionGWDE : YesNo
  + thresholdValueElementProtectionUses : YesNo
  + thresholdValueElementSalineIntrusion : YesNo
  + thresholdValueBackgroundLevels : ThresholdValueBackgroundLevels
}


class ThresholdValue:::forFixing{
  + gwThresholdIdentifier : wiseIdentifier
  + gwPollutantCode : SubstanceCode
  + thresholdValueRange : range [0..1]
  + thresholdValueUnit : UnitOfMeasure [0..1]
  + startingPointTrendReversal : range [0..1]
}

class GWPressures:::forFixing{
  «pending-discussion»
}

classDef default fill:white,stroke:#000;
classDef forFixing fill:white,stroke:#f00;