%%{init: {'theme': 'neutral'}}%%

flowchart LR

%% Surface Water Chemical Exemptions and Groundwater Chemical Exemptions
title@{ shape: braces, label: "Surface Water Chemical Exemptions \n and Groundwater Chemical Exemptions" }

%% Defining the nodes
		
initial([start])
final([end])

%% duplicate nodeS for just for flowchart readability
hasNoApplicableExemption_1("no exemption \n required"):::stateBlue
hasNoApplicableExemption_2("no exemption \n applicable"):::stateRed
hasNoApplicableExemption_3("no exemption \n required"):::stateBlue
hasNoApplicableExemption_4("no exemption \n applicable"):::stateRed

hasExemption44("Article 4(4) \n Extension of deadline"):::state
hasExemption45("Article 4(5) \n Less stringent objectives"):::state
hasExemption46("Article 4(6) \n Temporary deterioration"):::state
hasExemption47("Article 4(7) \n New modification/project"):::state

%% Defining the decisions

%% WE NEED THE LISTS!
is2026Substance{"2008 or 2013 \n priority substance?"}
is2013Substance{"2013 substance?"}

isCausingFailureIn2027{"Causing failure \n in 2027?"}
isDeteriorationExpected{"Deterioration expected \n beyond 2027?"}
isDeteriorationObserved{"Deterioration observed \n in 2027 or earlier?"}
isGoodStatusAchievable{"Is good status \n achievable?"}
isDelayDueToNaturalConditions{"Delay due to \n natural conditions?"}
isDelayDueToFeasibilityOrCost{"Delay due to \n technical feasibility OR \n disproportionate cost?"}

%% Flow to TERMINATORS

initial --> is2026Substance
hasNoApplicableExemption_1 --> final
hasNoApplicableExemption_2 --> final
hasNoApplicableExemption_3 --> final
hasNoApplicableExemption_4 --> final

hasExemption47 --> final 
hasExemption46 --> final 
hasExemption45 --> final 
hasExemption44 --> final 

%% THE IMPORTANT PART STARTS HERE

    %% EXEMPTIONS DON'T APPLY TO 2026 SUBSTANCES
    is2026Substance ==> |no| hasNoApplicableExemption_1
    is2026Substance ==> |yes| isCausingFailureIn2027

    %% NO EXEMPTION POSSIBLE - If the status is unknown, then exemptions cannot be reported
    isCausingFailureIn2027 ==> |unknown| hasNoApplicableExemption_2

    %% NO EXEMPTION NEEDED - if the status is not failing and no deterioration is expected, then no exemption is needed
    isCausingFailureIn2027 ==> |no| isDeteriorationExpected
    isDeteriorationExpected ==> |no| hasNoApplicableExemption_3

    %% ARTICLE 4(7) - DETERIORATION DUE TO NEW MODIFICATION OR PROJECT
    isDeteriorationExpected ==> |"yes \n [new modification \n OR sustainable human development]"| hasExemption47
        
    %% ARTICLE 4(6) - DETERIORATION DUE TO ACCIDENTS OR FORCE MAJEURE OR NATURAL CAUSES
    isCausingFailureIn2027 ==> |yes| isDeteriorationObserved
    isDeteriorationObserved ==> |"yes \n [new modification \n OR sustainable human development]"| hasExemption47
    isDeteriorationObserved ==> |"yes \n [accidents  \n OR force majeure  \n OR natural causes]"| hasExemption46
    isDeteriorationObserved ==> |no| isGoodStatusAchievable

    %% ARTICLE 4(5) - LESS STRINGENT OBJECTIVES
    isGoodStatusAchievable ==>|no| hasExemption45

    %% ARTICLE 4(4) EXTENSION OF DEADLINE - NATURAL CONDITIONS
    isGoodStatusAchievable ==> |yes| isDelayDueToNaturalConditions
            
    isDelayDueToNaturalConditions ==> |yes| hasExemption44
            
    %% ARTICLE 4(5) EXTENSION OF DEADLINE - FEASIBILITY OR COST - ONLY FOR 2013 SUBSTANCES
    isDelayDueToNaturalConditions ==> |no| isDelayDueToFeasibilityOrCost
    isDelayDueToFeasibilityOrCost ==> |yes| is2013Substance

    is2013Substance ==> |yes| hasExemption44

    is2013Substance ==> |no| hasNoApplicableExemption_4

    isDelayDueToFeasibilityOrCost ==> |no| hasNoApplicableExemption_4
    

%% styling
classDef state stroke-width:4px,fill:transparent
classDef stateRed stroke:red,fill:transparent
classDef stateBlue stroke:blue,fill:transparent