---
config:
  class:
    hideEmptyMembersBox: true
  layout: dagre
  theme: neutral
---
classDiagram
direction LR
class Role{
<<enumeration>>
pressureAndImpactAnalysis
economicAnalysis
monitoringOfSurfaceWater
monitoringOfGroundwater
assessmentOfStatusOfSurfaceWater
assessmentOfStatusOfGroundwater
preparationOfRBMP
preparationOfProgrammeOfMeasures
implementationOfMeasures
publicParticipation
enforcementOfRegulations
coordinationOfImplementation
reportingToTheEuropeanCommission
}

classDef default fill:white,stroke:#000;
classDef forFixing fill:white,stroke:#f00;