classDiagram
    direction TB

    namespace CostRecovery4thCycleOfReporting{
        class CostRecovery {
            + euRBDCode: wiseIdentifier
            «Adequate Contribution»
            + adequateContributionAccount: YesNo
            + adequateContributionSectoral: YesNo
            «Polluter Pays Principle»
            + pppAccount: YesNo
            + pppERCBased: YesNo
            + pppTargetPolluters: YesNo
            «Incentives»
            + incentivesAccount: YesNo
            + incentivesEmpiricalInformation: YesNo
            + incentivesDifferentiated: YesNo [0..1]
            + incentivesWaterScarcityUse: YesNo
        }
    }

    namespace CostRecoveryPerService4thCycleOfReporting{
        class CostRecoveryPerService {
            + euRBDCode: wiseIdentifier
            + waterService: WFDWaterService
            «Cost Recovery Principle Application»
            + costRecoveryFull: YesNoNotApplicable
            + costRecoveryCorroborated: YesNo [0..1]
            «Justification»
            + nationalMethodologyApplied: YesNo [0..1]
            + justificationLessFullRecovery: YesNo [0..1]
            + justificationFactor: string4000 [0..1]
            + justificationSectoralInformation: YesNo [0..1]
            «Exemption»
            + article94Exemption: YesNo [0..1]
            + article94Justification: YesNo [0..1]
        }
    }