classDiagram
    direction TB

    class VolumeRevenueCostPerService {
        + geo: wiseIdentifier [1]
        + time: Year [1]
        + dimension: VolumeRevenueCostCodelist value [1]
        + obs_value: NonNegativeValue [1]
        + obs_unit: UnitOfMeasureCodeList [1]
        + obs_status: ObservationStatusCode [0..1]
        + obs_comment: Text4000 [0..1]
    }