---
config:
  class:
    hideEmptyMembersBox: true
  layout: dagre
  theme: neutral
---

classDiagram
    direction TB

    class CostRecovery {
        + euRBDCode: wiseIdentifier

        --Adequate Contribution--

        + adequateContributionAccount: YesNo
        + adequateContributionSectoral: YesNo

        --Polluter Pays Principle--

        + pppAccount: YesNo
        + pppERCBased: YesNo
        + pppTargetPolluters: YesNo 

        --Incentives--
        + incentivesAccount: YesNo 
        + incentivesEmpiricalInformation: YesNo 
        + incentivesDifferentiated: YesNo [0..1]
        + incentivesWaterScarcityUse: YesNo 
    }

    class CostRecoveryPerService {
        + euRBDCode: wiseIdentifier 
        + waterService: WFDWaterService

        --Cost Recovery Principle Application--

        + costRecoveryFull: YesNoNotApplicable
        + costRecoveryCorroborated: YesNo [0..1]

        --Justification--

        + nationalMethodologyApplied: YesNo [0..1]
        + justificationLessFullRecovery: YesNo [0..1]
        + justificationFactor: String4000 [0..1]
        + justificationSectoralInformation: YesNo [0..1]

        --Exemption--

        + article94Exemption: YesNo [0..1]
        + article94Justification: YesNo [0..1]
    }

    class VolumeRevenueCostPerService {
        + geo: wiseIdentifier 
        + time: Year 
        + dimension: VolumeRevenueCost
        + obs_value: nonNegativeValue
        + obs_unit: UnitOfMeasureCode
        + obs_status: ObservationStatus [0..1]
        + obs_comment: String4000 [0..1]
    }

classDef default fill:white,stroke:#000;
classDef forFixing fill:white,stroke:#f00;
