---
config:
  class:
    hideEmptyMembersBox: true
  layout: dagre
  theme: neutral
---
classDiagram
    direction TB

    class VolumeRevenueCostPerService {
        + geo: wiseIdentifier 
        + time: Year 
        + dimension: VolumeRevenueCost 
        + obs_value: nonNegativeValue
        + obs_unit: UnitOfMeasure 
        + obs_status: ObservationStatus [0..1]
        + obs_comment: Text4000 [0..1]
    }

classDef default fill:white,stroke:#000;
classDef forFixing fill:white,stroke:#f00;