classDiagram
    direction TB

    class VolumeRevenueCostPerService {
        + euRBDCode: wiseIdentifier 
        + phenomenonTimePeriod: gYear
        + observedProperty: VolumeRevenueCost
        + resultObservedValue: nonNegativeValue
        + resultUnit: UnitOfMeasure
        + resultObservationStatus: ObservationStatusCode [0..1]
        + remarks: string4000 [0..1]
    }