classDiagram
    direction TB

    class VolumeRevenueCostPerService {
        + geo: wiseIdentifier [1]
        + time: Year [1]
        + dimension: VolumeRevenueCostCodelist value [1]
        + cbs_value: NonNegativeValue [1]
        + cbs_unit: UnitOfMeasureCodeList [1]
        + cbs_status: ObservationStatusCode [0..1]
        + cbs_comment: Text(4000) [0..1]
    }