%%{init: {'theme': 'neutral'}}%%

flowchart LR

%% Groundwater Quantitative Status Exemptions
title@{ shape: braces, label: "Groundwater Quantitative <br/>Status Exemptions" }

%% Defining the nodes
		
initial([start])
final([end])

%% duplicate nodeS for just for flowchart readability
hasNoApplicableExemption_1("no exemption <br/>applicable"):::stateRed
hasNoApplicableExemption_2("no exemption <br/>required"):::stateBlue
hasNoApplicableExemption_3("no exemption <br/>applicable"):::stateRed

hasExemption44n("Article 4(4) <br/> Extension of deadline (natural conditions)"):::state
hasExemption45("Article 4(5) <br/> Less stringent objectives"):::state
hasExemption46("Article 4(6) <br/> Temporary deterioration"):::state
hasExemption47("Article 4(7) <br/> New modification/project"):::state
hasExemption47a("Article 4(7a) <br/> Short-term impact"):::state

%% Defining the decisions

isQuantitativeStatusIn2027{"Quantitative Status <br/>in 2027?"}
isDeteriorationExpected{"Deterioration <br/>expected <br/>beyond 2027?"}
isDeteriorationObserved{"Deterioration <br/>observed <br/>in 2027 or earlier?"}
isDeteriorationCause{"Is deterioration <br/> caused by?"}
isGoodStatusAchievable{"Is good status <br/>achievable?"}
isUnfeasibleOrCostly{"Are measures <br/>unfeasible or <br/>disproportionately costly?"}
isDelayDueToNaturalConditions{"Delay due <br/>to natural conditions?"}

%% Flow to TERMINATORS

initial --> isQuantitativeStatusIn2027
hasNoApplicableExemption_1 --> final
hasNoApplicableExemption_2 --> final
hasNoApplicableExemption_3 --> final
hasExemption47 --> final 
hasExemption47a --> final 
hasExemption46 --> final 
hasExemption45 --> final 
hasExemption44n --> final 

%% THE IMPORTANT PART STARTS HERE

%% NO EXEMPTION POSSIBLE - If the status is unknown, then exemptions cannot be reported
isQuantitativeStatusIn2027 ==>|unknown|hasNoApplicableExemption_1

%% NO EXEMPTION NEEDED - if the status is not failing and no deterioration is expected, then no exemption is needed
isQuantitativeStatusIn2027 ==>|not failing|isDeteriorationExpected
isDeteriorationExpected ==>|no|hasNoApplicableExemption_2

%% ARTICLE 4(7) - DETERIORATION DUE TO NEW MODIFICATION OR PROJECT
isDeteriorationExpected ==> |yes|isDeteriorationCause
isDeteriorationCause ==> |"[new modification <br/> OR sustainable human development]"|hasExemption47
isDeteriorationCause ==> |"[short-term impact]"|hasExemption47a

%% ARTICLE 4(6) - DETERIORATION DUE TO ACCIDENTS OR FORCE MAJEURE OR NATURAL CAUSES
isQuantitativeStatusIn2027 ==>|failing|isDeteriorationObserved
isDeteriorationObserved ==>|"yes <br/>[other causes]"|isDeteriorationCause
isDeteriorationObserved ==>|"yes <br/>[accidents <br/>OR force majeure <br/>OR natural causes]"|hasExemption46
isDeteriorationObserved ==>|no|isGoodStatusAchievable

%% ARTICLE 4(5) - LESS STRINGENT OBJECTIVES
isGoodStatusAchievable ==>|no|isUnfeasibleOrCostly
isUnfeasibleOrCostly ==> |yes|hasExemption45
isUnfeasibleOrCostly ==> |no|hasNoApplicableExemption_3

%% ARTICLE 4(4) EXTENSION OF DEADLINE - NATURAL CONDITIONS
isGoodStatusAchievable ==>|yes|isDelayDueToNaturalConditions

%% ARTICLE 4(5) EXTENSION OF DEADLINE - FEASIBILITY OR COST - NO EXEMPTION POSSIBLE
isDelayDueToNaturalConditions ==>|no|hasNoApplicableExemption_3
isDelayDueToNaturalConditions ==>|yes|hasExemption44n

%% styling
classDef state stroke-width:4px,fill:transparent
classDef stateRed stroke:red,fill:transparent
classDef stateBlue stroke:blue,fill:transparent