%%{init: {'theme': 'default'}}%%
classDiagram 
namespace SWMET{
class SWExemptions ["«XSDcomplexType»
SWExemptions"]{
  «XSElement»
  + swExemption44Impact: SignificantImpactType_Enum [1..*]
  + swExemption44Driver: Driver_Enum [1..*]
  + swExemption45Impact: SignificantImpactType_Enum [1..*]
  + swExemption45Driver: Driver_Enum [1..*]
  + swDisproportionateCost: YesNoCode_Enum
  + swDisproportionateCostScale: GeographicalScale_Enum [0..*]
  + swDisproportionateCostAnalysis: DisproportionateCostAnalysis_Enum [0..*]
  + swDisproportionateCostAlternativeFinancing: DisproportionateCostAlternativeFinancing_Enum [0..*]
  + swDisproportionateCostOtherEULegislation: YesNoCode_Enum [0..1]
  + swTechnicalInfeasibility: TechnicalInfeasibility_Enum [1..*]
  + swNaturalConditions: SWNaturalConditions_Enum [1..*]
  + swExemption46: Exemption46_Enum [1..*]
  + swExemption47: Exemption47_Enum [1..*]
  + swExemptionsTransboundary: YesNoNotApplicable_Union_Enum
  + swExemptionsReference: ReferenceType [1..*]
  + driversSWExemptionsReference: ReferenceType [1..*]
}
}
namespace GWMET{
class GWExemptions["«XSDcomplexType» GWExemptions"]{
  «XSDElement»
  + gwExemption44Impact: SignificantImpactType_Enum [1..*]
  + gwExemption44Driver: Driver_Enum [1..*]
  + gwExemption45Impact: SignificantImpactType_Enum [1..*]
  + gwExemption45Driver: Driver_Enum [1..*]
  + gwDisproportionateCost: YesNoCode_Enum
  + gwDisproportionateCostScale: GeographicalScale_Enum [0..*]
  + gwDisproportionateCostAnalysis: DisproportionateCostAnalysis_Enum [0..*]
  + gwDisproportionateCostAlternativeFinancing: DisproportionateCostAlternativeFinancing_Enum [0..*]
  + gwDisproportionateCostOtherEULegislation: YesNoCode_Enum [0..1]
  + gwTechnicalInfeasibility: TechnicalInfeasibility_Enum [1..*]
  + gwNaturalConditions: GWNaturalConditions_Enum [1..*]
  + gwExemption46: Exemption46_Enum [1..*]
  + gwExemption47: Exemption47_Enum [1..*]
  + gwExemptionsTransboundary: YesNoNotApplicable_Union_Enum
  + gwExemptionsReference: ReferenceType [1..*]
  + driversGWExemptionsReference: ReferenceType [1..*]
}
}
