%%{init: {'theme': 'neutral'}}%%
classDiagram
class SWEcologicalExemption{
    + euSurfaceWaterBodyCode : wiseIdentifier
    + qeCode : QualityElement 
    / exemptionType : ExemptionType
    + exemptionRationale : ExemptionRationale [1..n]
    + exemptionPeriod : ExemptionPeriod
    + exemptionReference : referenceIdentifier [0..1]
    + significantPressureType : PressureType [1..n]
}