---
config:
  class:
    hideEmptyMembersBox: true
  layout: dagre
  theme: neutral
  themeVariables:
    noteBkgColor: LightYellow
    noteTextColor: black 
---
classDiagram
direction TB

class GWLinkSurfaceWaterBody{
    + euGroundWaterBodyCode: wiseIdentifier
    + euSurfaceWaterBodyCode: wiseIdentifier
    + linkType: GroundwaterSurfaceWaterLink
}

class GWNaturalBackgroundLevel{
    + euGroundWaterBodyCode: wiseIdentifier
    + parameterCode: Parameter
    + naturalBackgroundLevelSet: YesNo
    + parameterValue: range [0..1]
    + parameterUnit: UnitOfMeasure [0..1]
}

class GroundWaterBody{
    + euGroundWaterBodyCode: wiseIdentifier
    + aquiferType: AquiferMediaTypeValue
    + aquiferProductivity: AquiferProductivity
    + groundWaterBodyTransboundary: YesNo
    + linkSurfaceWaterBody: YesNo
    + linkTerrestrialEcosystem: YesNoUnknown
}

class GWQuantitativeStatus{
    + euGroundWaterBodyCode: wiseIdentifier
    + gwQuantitativeStatusValue: QuantitativeStatus
    + gwQuantitativeAssessmentPeriod: range
    + gwQuantitativeAssessmentConfidence: AssessmentConfidence
    + gwQuantitativeAssessmentMethod: AssessmentMethod [1..n]
    + gwGroupingIdentifier: wiseIdentifier [0..n]

    + gwAtRiskQuantitative: YesNo
}

class GWPressureImpact{
    + euGroundWaterBodyCode: wiseIdentifier
    + gwPressureType: PressureType [0..1]
    + gwImpactType: ImpactType  [0..1]
}

class GWStatus{
    
    + euGroundWaterBodyCode: wiseIdentifier
    + gwQuantitativeStatusValue: QuantitativeStatus
    + gwChemicalStatusValue: ChemicalStatus

    + gwQuantitativeReasonsForFailure: ReasonForFailure [1..n]
    + gwQuantitativeReasonsForRisk: ReasonForFailure [1..n]
    + gwChemicalReasonsForFailure: ReasonForFailure [1..n]
} 

class GWPollutant{
    + euGroundWaterBodyCode: wiseIdentifier
    + gwPollutantCode: Parameter

    + gwThresholdIdentifier: wiseIdentifier
    + gwGroupingIdentifier: wiseIdentifier [0..n]
    + gwPollutantCausingFailure: YesNoUnknown
    + gwPollutantAssessmentPeriod: range
    + gwPollutantAssessmentConfidence: AssessmentConfidence 
    + gwPollutantAssessmentMethod: AssessmentMethod [1..n]

    + gwPollutantCausingRisk: YesNoUnknown

    + gwPollutantUpwardTrend: YesNoUnknownNotAssessed
    + gwPollutantTrendReversal: YesNoUnknownNotApplicableNotAssessed
    + gwPollutantTrendReversalProcess: YesNoUnknownNotApplicableNotAssessed

}

class GWGrouping{
    + gwGroupingIdentifier: wiseIdentifier
    + euGroundWaterBodyCode: wiseIdentifier
}

GroundWaterBody "1" -- "1" GWStatus    
GWStatus "1" -- "0..1" GWQuantitativeStatus
GWStatus "1" -- "0..n" GWPollutant
GWStatus "1" -- "0..n" GWPressureImpact

GWQuantitativeStatus ..> GWGrouping: gwGroupingIdentifier
GWPollutant ..> GWGrouping: gwGroupingIdentifier

GWLinkSurfaceWaterBody "0..n" -- GroundWaterBody: {linkSurfaceWaterBody = 'Yes'}
GWNaturalBackgroundLevel "0..n" -- GroundWaterBody

GWNaturalBackgroundLevel .. GWPollutant: {quality control}

%% note for GWPollutant "GroundwaterMethodologies::ThresholdValue.gwThresholdIdentifier"

classDef default fill:white,stroke:#000;
classDef forFixing fill:white,stroke:#f00;
