---
config:
  class:
    hideEmptyMembersBox: true
  layout: dagre
  theme: neutral
---
classDiagram
direction TB

class GWType {
  + gwTypeIdentifier: wiseIdentifier
}

class GWPollutant ["GroundWaterDataset::GWPollutant"]:::otherDataset{
  + euGroundWaterBodyCode
  + gwPollutantCode
  + gwThresholdIdentifier
}

class GWThresholdValue{
  + gwThresholdIdentifier: wiseIdentifier
  + parameterCode: Parameter
  + thresholdValueRange: range 
  + thresholdValueUnit: UnitOfMeasure 
  + naturalBackgroundLevelSet: YesNoNotApplicable
  + startingPointTrendReversal: range [0..1]
  «reference»
  + gwThresholdReference: referenceCode [0..n]
}

class GWThreshold_GWType{
  + gwThresholdIdentifier: wiseIdentifier
  + gwTypeIdentifier: wiseIdentifier
}

class GWNaturalBackgroundLevel{
  + gwTypeIdentifier: wiseIdentifier
  + parameterCode: Parameter
  + parameterValue: range  
  + parameterUnit: UnitOfMeasure
}

GWPollutant ..> GWThresholdValue 
GWThresholdValue "1" -- "0..n" GWThreshold_GWType 
GWThreshold_GWType "0..n" -- "1" GWType 
GWType "1" -- "0..n" GWNaturalBackgroundLevel

classDef default fill:white,stroke:#000;
classDef forFixing fill:white,stroke:#f00;
classDef otherDataset fill:lavender,stroke:#000;