---
config:
  class:
    hideEmptyMembersBox: true
  layout: dagre
  theme: neutral
  themeVariables:
    noteBkgColor: LightYellow
    noteTextColor: black 
---
classDiagram

class GWMethodologies {
  + euRBDCode : wiseIdentifier
  + gwCharacterisationReference : referenceCode
  + trendAssessmentPerformed : YesNo
  + trendAssessmentTimeSeries : range [0..1]
  + trendAssessmentStatisticalMethod : TrendStatisticalMethod [0..1]
  + additionalTrendAssessment : YesNo
  + trendReversalMethodology : YesNo
  + thresholdValueElementProtectionEcosystem : YesNo
  + transboundaryThresholdValues : YesNoNotApplicable
  + thresholdValueElementProtectionGWDE : YesNo
  + thresholdValueElementProtectionUses : YesNo
  + thresholdValueElementSalineIntrusion : YesNo
}

class GWPressureAssessment{
  + euRBDCode : wiseIdentifier
  + gwPressure : PressureType
  + gwPressureAssessmentMethod : PressureAssessmentMethod
  + gwSignificanceDefinition : YesNoNotApplicable
  + gwSignificanceLinkFailure : YesNoNotApplicable
}

class ThresholdValue{
  + gwThresholdIdentifier : wiseIdentifier
  + parameterCode : Parameter
  + thresholdValueDefined : YesNo
  + thresholdValueRange : range [0..1]
  + thresholdValueUnit : UnitOfMeasure [0..1]
  + startingPointTrendReversal : range [0..1]
  + naturalBackgroundLevelSet : YesNoNotApplicable
  + nblValueRange : range  [0..1] 
}

class PressureAssessmentMethod{
<<enumeration>>
numericalTools
expertJudgment
combinationOfBoth
notAssessed 
}

class TrendStatisticalMethod{
<<enumeration>>
statisticalSignificanceTrendDetection
confidenceIntervalTrendMagnitude
none
}

GWPressureAssessment .. PressureAssessmentMethod : gwPressureAssessmentMethod
GWMethodologies .. TrendStatisticalMethod : trendAssessmentStatisticalMethod

note for ThresholdValue "GroundwaterDataset::GWPollutant.gwThresholdIdentifier"

classDef default fill:white,stroke:#000;
classDef forFixing fill:white,stroke:#f00;