---
config:
  class:
    hideEmptyMembersBox: true
  layout: dagre
  theme: default
---
classDiagram

class GWMethodologies {
  + gwCharacterisationReference: ReferenceType [1..*]
  + diminutionDamage: YesNoNotApplicable_Union_Enum
  + methodCriterionExtentExceedance: MethodCriterionExtentExceedance_Enum
  + proportionExceedanceAllowed: NumberDecimal0100Type [0..1]
  + impactsGWAbstractionBalance: YesNoCode_Enum
  + impactsGWAbstractionSWObjective: YesNoCode_Enum
  + impactsGWAbstractionSWDiminutionStatus: YesNoCode_Enum
  + impactsGWAbstractionDamageGWDE: YesNoCode_Enum
  + impactsGWAbstractionSalineIntrusion: YesNoCode_Enum
  + availableGroundwaterResource: YesNoPartially_Union_Enum
  + needsTerritorialEcosystems: YesNoNotApplicable_Union_Enum
  + balanceRechargeAbstraction: BalanceRechargeAbstraction_Enum
  + trendAssessmentPerformed: YesNoCode_Enum
  + trendAssessmentMethodology: YesNoCode_Enum [0..1]
  + timeSeries: YearRangeType [0..1]
  + statisticalElements: StatisticalElements_Enum [0..1]
  + additionalTrendAssessment: YesNoCode_Enum
  + trendReversalMethodology: YesNoCode_Enum
  + thresholdValueElementProtectionEcosystem: YesNoCode_Enum
  + thresholdValueElementProtectionGWDE: YesNoCode_Enum
  + thresholdValueElementProtectionUses: YesNoCode_Enum
  + thresholdValueElementSalineIntrusion: YesNoCode_Enum
  + thresholdValueBackgroundLevels: ThresholdValueBackgroundLevels_Enum
  + transboundaryGWBPresent: YesNoCode_Enum
  + transboundaryThresholdValues: YesNoCode_Enum
  + gwMethodologiesChemicalStatusClassificationReference: ReferenceType [1..*]
  + gwMethodologiesQuantitativeClassificationReference: ReferenceType [1..*]
  + gwMethodologiesTransboundaryReference: ReferenceType [0..*]
}

class GWPressures{
  + gwPressuresNotAssessed: SignificantPressureType_Enum [1..*]
  + gwSignificantPressurePointSourceTools: SignificantPressureTools_Enum
  + gwSignificantPressureDiffuseSourceTools: SignificantPressureTools_Enum
  + gwSignificantPressureWaterAbstractionTools: SignificantPressureTools_Enum
  + gwSignificantPressureArtificialRecharge: SignificantPressureTools_Enum
  + gwSignificantPressureOtherSourceTools: SignificantPressureTools_Enum
  + gwSignificanceDefinition: YesNoCode_Enum
  + gwSignificanceLinkFailure: YesNoCode_Enum
  + gwPressuresReference: ReferenceType [1..*]
}


class ThresholdValue{
  + pollutantIndicatorCode: ChemicalSubstances_Union_Enum
  + pollutantIndicatorCodeOther: OtherType [0..1]
  + thresholdValueRange: ThresholdType [0..1]
  + thresholdValueUnit: UnitOfMeasure_Enum
  + thresholdValueDerivedFromCV: YesNoCode_Enum
  + cvDrinkingWaterValueRange: ThresholdType [0..1]
  + cvDrinkingWaterValueUnit: UnitOfMeasure_Enum [0..1]
  + cvIrrigationValueRange: ThresholdType [0..1]
  + cvIrrigationValueUnit: UnitOfMeasure_Enum [0..1]
  + cvIndustryValueRange: ThresholdType [0..1]
  + cvIndustryValueUnit: UnitOfMeasure_Enum [0..1]
  + cvOtherValueRange: ThresholdType [0..1]
  + cvOtherValueUnit: UnitOfMeasure_Enum [0..1]
  + thresholdValueScale: GeographicalScale_Enum
  + startingPointTrendReversal: ThresholdType
}


class GWMET {
  + countryCode: CountryCode_Enum
  + euRBDCode: FeatureUniqueEUCodeType
}

GWMethodologies <-- GWMET : 1..1
GWPressures <-- GWMET : 1..1
ThresholdValue <-- GWMET : *..0