---
config:
  class:
    hideEmptyMembersBox: true
  layout: dagre
  theme: neutral
---
classDiagram
direction TB

class LinkSurfaceWaterBody{
    + euGroundWaterBodyCode : wiseIdentifier
    + euSurfacedWaterBodyCode : wiseIdentifier
    + linkType : GroundwaterSurfacewaterLinkTypeValue [0..1]
}

class GroundWaterBody{
    + euGroundWaterBodyCode : wiseIdentifier
    + aquiferType : AquiferMediaTypeValue
    + aquiferProductivity : AquiferProductivityValue
    + groundWaterBodyTransboundary : YesNo
    + linkSurfaceWaterBody : YesNo
    + linkTerrestrialEcosystem : YesNoUnknown
}

class GWPressureImpact{
    + euGroundWaterBodyCode : wiseIdentifier
    + gwPressureType : PressureType [0..1]
    + gwImpactType : ImpactType  [0..1]
}


class GWQuantitativeStatus:::forFixing{
    + euGroundWaterBodyCode : wiseIdentifier
    + gwQuantitativeStatusValue : QuantitativeStatusValue
    + gwQuantitativeAssessmentPeriod : range
    + gwQuantitativeAssessmentConfidence : AssessmentConfidenceValue
    + gwQuantitativeAssessmentMethod : AssessmentMethodValue [1..n]
    + gwQuantitativeAssessmentGrouping : gwGroupCode [0..n]
}

class GroundWaterBodyStatus{
    
    + euGroundWaterBodyCode : wiseIdentifier
    / gwQuantitativeStatusValue : QuantitativeStatusValue
    / gwChemicalStatusValue : ChemicalStatusValue

    + gwQuantitativeReasonsForFailure : ReasonForFailureValue [1..n]
    + gwChemicalReasonsForFailure : ReasonForFailureValue [1..n]
} 

class GWPollutant:::forFixing{
    + euGroundWaterBodyCode : wiseIdentifier
    + gwPollutantCode : SubstanceCode
    + gwPollutantCausingFailure : YesNoUnknown
    + gwPollutantAssessmentPeriod : range
    + gwPollutantAssessmentConfidence : AssessmentConfidenceValue 
    + gwPollutantAssessmentMethod : AssessmentMethodValue [1..n]
    + gwPollutantAssessmentGrouping : gwGroupCode [0..n]

    «trend»
    + gwPollutantUpwardTrend : YesNoUnknown
    + gwPollutantTrendReversal : YesNoUnknownNotApplicable
    + gwPollutantTrendReversalProcess : YesNoUnknownNotApplicable

    «background-level»
    + gwPollutantBackgroundLevelSet : YesNo
    + gwPollutantBackgroundLevelValue : range [0..1] 
    + gwPollutantBackgroundLevelUnit : UnitOfMeasure [0..1] 
}

class GWGroup:::forFixing{
    + gwGroupCode : wiseIdentifier
    + euGroundWaterBodyCode : wiseIdentifier
}

GroundWaterBody -- GroundWaterBodyStatus    
GroundWaterBodyStatus --  GWQuantitativeStatus
GroundWaterBodyStatus -- "0..n" GWPollutant
GroundWaterBodyStatus -- "0..n" GWPressureImpact

GWQuantitativeStatus .. GWGroup
GWPollutant .. GWGroup

LinkSurfaceWaterBody "0..n" -- "1" GroundWaterBody : {linkSurfaceWaterBody = 'Yes'}

classDef default fill:white,stroke:#000;
classDef forFixing fill:white,stroke:#f00;