---
config:
  class:
    hideEmptyMembersBox: true
  layout: dagre
  theme: neutral
---
classDiagram
direction LR

class ReasonForFailure{
<<enumeration>>
surfaceWater
groundWaterDependentTerrestrialEcosystem
salineOrOtherIntrusion
waterBalance
drinkingWaterProtectionArea
waterQualityAssessment
notApplicable
}

classDef default fill:white,stroke:#000;
classDef forFixing fill:white,stroke:#f00;
