---
config:
  class:
    hideEmptyMembersBox: true
  layout: dagre
  theme: neutral
  themeVariables:
    noteBkgColor: LightYellow
    noteTextColor: black 
---
classDiagram
direction TB

class GWLinkSurfaceWaterBody{
    + euGroundWaterBodyCode : wiseIdentifier
    + euSurfacedWaterBodyCode : wiseIdentifier
    + linkType : GroundwaterSurfaceWaterLink
}

class GWNaturalBackgroundLevel{
    + euGroundWaterBodyCode : wiseIdentifier
    + parameterCode : ParameterCode
    + parameterValue : range  
    + parameterUnit : UnitOfMeasure
}

class GroundWaterBody{
    + euGroundWaterBodyCode : wiseIdentifier
    + aquiferType : AquiferMediaTypeValue
    + aquiferProductivity : AquiferProductivity
    + aquiferLithology : LithologyValue
    + groundWaterBodyTransboundary : YesNo
    + linkSurfaceWaterBody : YesNo
    + linkTerrestrialEcosystem : YesNoUnknown
}

class GWQuantitativeStatus{
    + euGroundWaterBodyCode : wiseIdentifier
    + gwQuantitativeStatusValue : QuantitativeStatus
    + gwQuantitativeAssessmentPeriod : range
    + gwQuantitativeAssessmentConfidence : AssessmentConfidence
    + gwQuantitativeAssessmentMethod : AssessmentMethod [1..n]
    + gwGroupIdentifier : wiseIdentifier [0..n]
}

class GWPressureImpact{
    + euGroundWaterBodyCode : wiseIdentifier
    + gwPressureType : PressureType [0..1]
    + gwImpactType : ImpactType  [0..1]
}

class GWStatus{
    
    + euGroundWaterBodyCode : wiseIdentifier
    / gwQuantitativeStatusValue : QuantitativeStatus
    / gwChemicalStatusValue : ChemicalStatus

    + gwQuantitativeReasonsForFailure : ReasonForFailure [1..n]
    + gwChemicalReasonsForFailure : ReasonForFailure [1..n]
} 

class GWPollutant{
    + euGroundWaterBodyCode : wiseIdentifier
    + gwPollutantCode : Parameter

    + gwPollutantCausingFailure : YesNoUnknown
    + gwPollutantAssessmentPeriod : range
    + gwPollutantAssessmentConfidence : AssessmentConfidence 
    + gwPollutantAssessmentMethod : AssessmentMethod [1..n]

    + gwPollutantUpwardTrend : YesNoUnknownNotAssessed
    + gwPollutantTrendReversal : YesNoUnknownNotApplicableNotAssessed
    + gwPollutantTrendReversalProcess : YesNoUnknownNotApplicableNotAssessed

    + gwThresholdIdentifier : wiseIdentifier
    + gwGroupIdentifier : wiseIdentifier [0..n]
}

class GWGrouping{
    + gwGroupIdentifier : wiseIdentifier
    + euGroundWaterBodyCode : wiseIdentifier
}

GroundWaterBody -- GWStatus    
GWStatus --  GWQuantitativeStatus
GWStatus -- "0..n" GWPollutant
GWStatus -- "0..n" GWPressureImpact

GWQuantitativeStatus "0..n" .. "0..n" GWGrouping : gwGroupIdentifier
GWPollutant "0..n" .. "0..n" GWGrouping : gwGroupIdentifier

GWLinkSurfaceWaterBody "0..n" -- GroundWaterBody : {linkSurfaceWaterBody = 'Yes'}
GWNaturalBackgroundLevel "0..n" -- GroundWaterBody

%% note for GWPollutant "GroundwaterMethodologies::ThresholdValue.gwThresholdIdentifier"

classDef default fill:white,stroke:#000;
classDef forFixing fill:white,stroke:#f00;
