---
config:
  class:
    hideEmptyMembersBox: true
  layout: dagre
  theme: neutral
---
classDiagram
direction LR

class GroundWaterBody{
    + euGroundWaterBodyCode : wiseIdentifier
    + aquiferType : AquiferType
    + aquiferProductivity : AquiferProductivity
    + groundWaterBodyTransboundary : YesNo
    + linkSurfaceWaterBody : YesNo
    + linkTerrestrialEcosystem : YesNoUnknown
}

class LinkSurfaceWaterBody:::forFixing{
    + euGroundWaterBodyCode : wiseIdentifier
    + euSurfacedWaterBodyCode : wiseIdentifier

    «pending-further-discussion»
    + linkType : CodelistToBeDefined [0..1]
}

class GWPressureImpact:::forFixing{
    + euGroundWaterBodyCode : wiseIdentifier
    + gwPressureType : PressureType [0..1]
    + gwImpactType : ImpactType  [0..1]
}

class GWQuantitativeStatus:::forFixing{
    + euGroundWaterBodyCode : wiseIdentifier
    + gwQuantitativeStatusValue : QuantitativeStatus
    + gwQuantitativeAssessmentPeriod : range
    + gwQuantitativeAssessmentConfidence : AssessmentConfidence

    «pending-discussion-analogy-with-sw»
    + gwQuantitativeAssessmentMethod : AssessmentMethod 
    + gwQuantitativeAssessmentGrouping : euGroundWaterBodyCode [0..n]
}

class GroundWaterBodyStatus:::forFixing{
    
    + euGroundWaterBodyCode : wiseIdentifier
    / gwQuantitativeStatusValue 
    / gwChemicalStatusValue 
    
    «pending-discussion-overlaps-with-pressures»
    + gwQuantitativeReasonsForFailure : QuantitativeFailure [0..*]
    + gwChemicalReasonsForFailure : ReasonsForFailure [0..*]
} 

class GWPollutant:::forFixing{
    + euGroundWaterBodyCode : wiseIdentifier
    + gwPollutantCode : SubstanceCode
    + gwPollutantCausingFailure : YesNoUnknown
    + gwPollutantAssessmentPeriod : range
    + gwPollutantAssessmentConfidence : AssessmentConfidence 

    «trend»
    + gwPollutantUpwardTrend : YesNoUnknown
    + gwPollutantTrendReversal : YesNoUnknownNotApplicable
    + gwPollutantTrendReversalProcess : YesNoUnknownNotApplicable

    «background-level»
    + gwPollutantBackgroundLevelSet : YesNo
    + gwPollutantBackgroundLevelValue : range [0..1] 
    + gwPollutantBackgroundLevelUnit : UnitOfMeasure [0..1] 

    «pending-discussion-analogy-with-sw»
    + gwPollutantAssessmentMethod : AssessmentMethod 
    + gwPollutantAssessmentGrouping : euGroundWaterBodyCode [0..n]

}

GroundWaterBody "0..n" -- "0..n" LinkSurfaceWaterBody : {if linkSurfaceWaterBody is Yes}

GroundWaterBody -- GroundWaterBodyStatus    
GroundWaterBodyStatus --  GWQuantitativeStatus
GroundWaterBodyStatus -- "0..n" GWPressureImpact 
GroundWaterBodyStatus -- "0..n" GWPollutant

classDef default fill:white,stroke:#000;
classDef forFixing fill:white,stroke:#f00;