---
config:
  class:
    hideEmptyMembersBox: true
  layout: dagre
  theme: neutral
  themeVariables:
    noteBkgColor: LightYellow
    noteTextColor: black 
---
classDiagram

class GWMethodologies {
  + euRBDCode : wiseIdentifier
  + gwCharacterisationReference : referenceCode
  + trendAssessmentPerformed : YesNo
  + trendAssessmentTimeSeries : range [0..1]
  + trendAssessmentStatisticalMethod : TrendStatisticalMethod [0..1]
  + additionalTrendAssessment : YesNo
  + trendReversalMethodology : YesNo
  + thresholdValueElementProtectionEcosystem : YesNo
  + transboundaryThresholdValues : YesNoNotApplicable
  + thresholdValueElementProtectionGWDE : YesNo
  + thresholdValueElementProtectionUses : YesNo
  + thresholdValueElementSalineIntrusion : YesNo
}

class GWPressureAssessment{
  + euRBDCode : wiseIdentifier
  + gwPressure : PressureType
  + gwPressureAssessmentMethod : PressureAssessmentMethod
  + gwSignificanceDefinition : YesNoNotApplicable
  + gwSignificanceLinkFailure : YesNoNotApplicable
}

class GWThresholdValue{
+ gwThresholdIdentifier : wiseIdentifier
+ parameterCode : Parameter
+ thresholdValueDefined : YesNo
+ thresholdValueRange : range [0..1]
+ thresholdValueUnit : UnitOfMeasure [0..1]
+ naturalBackgroundLevelSet : YesNoNotApplicable
+ nblValueRange : range  [0..1] 

«trend-reversal-measures»
+ startingPointTrendReversal : range [0..1]
}

class GWPollutant ["GroundWaterDataset::GWPollutant"]:::otherDataset{
+ euGroundWaterBodyCode
+ gwPollutantCode
+ gwThresholdIdentifier
}

class PressureAssessmentMethod{
<<enumeration>>
numericalTools
expertJudgment
combinationOfBoth
notAssessed 
}

class TrendStatisticalMethod{
<<enumeration>>
statisticalSignificanceTrendDetection
confidenceIntervalTrendMagnitude
none
}

GWPressureAssessment .. PressureAssessmentMethod : gwPressureAssessmentMethod
GWMethodologies .. TrendStatisticalMethod : trendAssessmentStatisticalMethod

GWThresholdValue .. "1..n" GWPollutant : gwThresholdIdentifier

classDef default fill:white,stroke:#000;
classDef otherDataset fill:lightyellow,stroke:#000;
classDef forFixing fill:white,stroke:#f00;
