classDiagram

class Measure {
    + measureCode : wiselIdentifier [1]
    + measureName : String1000 [1]
    + measureReference : DocumentReference [0..1]

    + measureType : MeasureTypeCodelist value [1]
    + mainLegalInstrument : LegalInstrumentCodelist value [1]
    + mainKeyTypeOfMeasure : MainKeyTypeOfMeasureCodelist value [1]

    + mainPressureType : HierarchicalPressureTypeCodelist value [0..1]
    + mainSubstanceType : HierarchicalSubstanceTypeCodelist value [0..1]
    --link to sectorak plans--
    + msfdRelevance : YesNo [1]
    + floodsRelevance : YesNo [1]
    + natureRestorationRegulationRelevance : YesNo [1]
    + draughtManagementPlanRelevance : YesNo [1]
    + climateAdaptationPlanRelevance : YesNo [1]
    --geographical coverage--
    + geographicalCoverage : WFDGeographicCoverageCodelist value [1]
    + euRBDCode : wiselIdentifier [0..n]
    + waterCategory : HierarchicalWaterCategoryCodelist value [0..1]
    + protectedAreaType : ProtectedAreaTypeCodelist value [0..1]
    --temporal coverage--
    + implementationPeriod : YearRangeType [1]
    + implementationStatus : PlannedOngoingExecutedCancelledCodelist value [1]
}