---
config:
  class:
    hideEmptyMembersBox: true
  layout: dagre
  theme: neutral
---
classDiagram
direction TB

class TargetedQuestions{
    + euRBDCode: wiseIdentifier

    + basicMeasuresArt113c: MeasuresChanges
    + basicMeasuresArt113d: BasicMeasuresArt113d
    + basicMeasuresArt113ePermit: MeasureScope
    + basicMeasuresArt113eRegister: MeasureScope
    + basicMeasuresArt113eThreshold: BasicMeasuresArt113eThreshold
    + basicMeasuresArt113eImpoundment: BasicMeasuresArt113eImpoundment
    + basicMeasuresArt113f: MeasuresChanges
    + basicMeasuresArt113gPermit: MeasureScope
    + basicMeasuresArt113gRegister: MeasureScope
    + basicMeasuresArt113gThreshold: BasicMeasuresArt113gThreshold
    + basicMeasuresArt113hRules: BasicMeasuresArt113hRules
    + basicMeasuresArt113iPermit: YesNo 
    + basicMeasuresArt113iRegister: YesNo 
    + basicMeasuresArt113j: BasicMeasuresArt113j
    + basicMeasuresArt113k: YesNo 

    + waterReUseMeasure: YesNo
    + ecologicalFlowDerived: EcologicalFlow
    + ecologicalFlowImplemented: EcologicalFlow
    + climateChange: YesNo
    + climateChangeGuidance: YesNo
    + floodsDirective: YesNo
    + structuralMeasures: YesNo
    + msfdCoOrdination: YesNoNotRelevant
    + msfdAssessment: YesNoNotRelevant
    }

class MeasuresChanges{
    <<enumeration>>
    implementedInPreviousCycleAndNonePlanned
    inPreviousCycleAndNewMeasuresOrChangesPlanned
    noneInPreviousCycleButNewMeasuresOrChangesPlanned
    noneInPreviousCycleAndNonePlanned
    }

class MeasureScope{
    <<enumeration>>
    surfaceWater
    groundwater
    bothSurfaceAndGroundwater
    }

class BasicMeasuresArt113eThreshold{
    <<enumeration>>
    smallAbstractionsExemptedFromControls
    smallAbstractionDoNotRequirePermitButAreRegistered
    noThresholdForAbstractions
    }

class BasicMeasuresArt113eImpoundment{
    <<enumeration>>
    registerAndConcessionAuthorisationOrPermitting
    concessionAuthorisationOrPermitting
    registerOfImpoundments
    none
    }

class BasicMeasuresArt113gThreshold{
    <<enumeration>>
    smallDischargesExemptedFromControls
    smallDischargesDoNotRequirePermitButAreRegistered
    noThresholdForDischarges
    }

class BasicMeasuresArt113hRules{
    <<enumeration>>
    yesSameRulesInTheWholeRBD
    yesButOnlyInNitrateVulnerableZones
    yesButDifferentRulesInDifferentPartsOfTheRBD
    noGeneralBindingRules
    }

class BasicMeasuresArt113j{
    <<enumeration>>
    prohibitionOfAllDirectDischarges
    someDirectDischargesAreAuthorised
    noProhibitionOfDirectDischarges
    }

class EcologicalFlow{
    <<enumeration>>
    yesForAllRelevantWaterBodies
    partlyOngoingWork
    notYetOnlyNextCycle
    noAndNotPlanned
}

TargetedQuestions ..> MeasuresChanges
TargetedQuestions ..> MeasureScope
TargetedQuestions ..> BasicMeasuresArt113eThreshold
TargetedQuestions ..> BasicMeasuresArt113eImpoundment
TargetedQuestions ..> BasicMeasuresArt113gThreshold
TargetedQuestions ..> BasicMeasuresArt113hRules
TargetedQuestions ..> BasicMeasuresArt113j
TargetedQuestions ..> EcologicalFlow

classDef default fill:white,stroke:#000;
classDef forFixing fill:white,stroke:#f00;