classDiagram

class RiverBasinManagementPlan {
      + euRBDCode : wiseldentifier [1]
    + rbmpName : text1000 [1]
    + rbmpTimetablePublicationDate : Date [1]
    + rbmpProgrammePublicationDate : Date [1]
    + rbmpConsultationPublicationDate : Date [1]
    + rbmpInterimOverviewDate : Date [1]
    + rbmpDraftVersionDate : Date [1]
    + finalRBMPPublicationDate : Date [1]

    + subPlans : YesNo [1]
    + subPlansCoverage : SubPlansCodelist value [0..1]
    + subPlansReference : DocumentReference [0..n]

    + sea : YesNo [1]
    + seaReference : DocumentReference [0..n]

    + documentAvailability : YesNo [1]

    + ongoingStakeholderInvolvement : OngoingStakeholderInvolvementCodelist value [0..n]
    + stakeholderGroups : StakeholderGroupsCodelist value [0..n]

    + internationalCoordination : InternationalCoordinationCodelist value [0..1]
    + internationalCoordinationPublicParticipation : YesNo [0..1]
    + pomCoordinationArt5SWMI : CoordinationCodelist value [1]
    + pomCoordinationIRBMPPoM : CoordinationCodelist value [1]
    + pomCoordinationRoofReport : CoordinationCodelist value [1]
    + pomCoordinationFinancial : CoordinationCodelist value [1]

    + integrationFloodsDirective : YesNo [1]
    + coordinationFloodsDirective : YesNoNotApplicable [1]
    + coordinationMSFD : YesNoNotApplicable [1]

    + coordinationNRRReference : DocumentReference [1..n]
}

class Progress {
    + euRBDCode : wiseIdentifier [1]

    + previousRBMPMeasureStatus : PlannedOngoingExecutedCancelledCodelist value [1]
    + percentageInStatus : Percentage [1]

    + obstaclesGovernance : YesNo [1]
    + obstaclesDelays : YesNo [1]
    + obstaclesLackOfFinance : YesNo [1]
    + obstaclesLackOfMechanism : YesNo [1]
    + obstaclesMeasureNotEffective : YesNo [1]
    + obstaclesMeasureNotCostEffective : YesNo [1]
    + obstaclesExtremeEvents : YesNo [1]
}

class TargetedQuestions {
      + euRBDCode : wisedIdentifier [1]

    + basicMeasuresArt113c : BasicMeasuresChangesCodelist value [1]
    + basicMeasuresArt113d : BasicMeasuresArt113dCodelist value [1]
    + basicMeasuresArt113ePermit : BasicMeasuresCodelist value [1]
    + basicMeasuresArt113gRegister : BasicMeasuresCodelist value [1]
    + basicMeasuresArt113hThreshold : BasicMeasuresArt113hThresholdCodelist value [1]
    + basicMeasuresArt113eImpoundment : BasicMeasuresArt113iImpoundmentCodelist value [1]
    + basicMeasuresArt113f : BasicMeasuresChangesCodelist value [1]

    + basicMeasuresArt113gPermit : BasicMeasuresCodelist value [1]
    + basicMeasuresArt113gRegister : BasicMeasuresCodelist value [1]
    + basicMeasuresArt113gThreshold : BasicMeasuresArt113hThresholdCodelist value [1]
    + basicMeasuresArt113hRules : BasicMeasuresArt113hRulesCodelist value [1]

    + basicMeasuresArt113iPermit : YesNo [1]
    + basicMeasuresArt113iRegister : YesNo [1]
    + basicMeasuresArt113j : BasicMeasuresArt113jCodelist value [1]
    + basicMeasuresArt113k : YesNo [1]

    + waterReuseMeasure : YesNo [1]
    + ecologicalFlow : EcologicalFlowCodelist value [1]
    + ecologicalFlowImplementation : EcologicalFlowImplementationCodelist value [1]
    + climateChange : YesNo [1]
    + climateChangeGuidance : YesNo [1]
    + floodsDirective : YesNo [1]
    + structuralMeasures : YesNo [1]
    + msfdCoOrdination : YesNoNotRelevant [1]
    + msfdAssessment : YesNoNotRelevant [1]
}

class Measure {
   + measureCode : wiselIdentifier [1]
    + measureName: text1000 [1]
    + measureReference : DocumentReference [0..1]

    + measureType : MeasureTypeCodelist value [1]
    + mainLegalInstrument : LegalInstrumentCodelist value [1]
    + mainKeyTypeOfMeasure : MainKeyTypeOfMeasureCodelist value [1]

    + mainPressureType : HierarchicalPressureTypeCodelist value [0..1]
    + mainSubstanceType : HierarchicalSubstanceTypeCodelist value [0..1]

    + msfdRelevance : YesNo [1]
    + floodsRelevance : YesNo [1]
    + natureRestorationRegulationRelevance : YesNo [1]
    + draughtManagementPlanRelevance : YesNo [1]
    + climateAdaptationPlanRelevance : YesNo [1]

    + geographicalCoverage : WFDGeographicCoverageCodelist value [1]
    + euRBDCode : wiselIdentifier [0..n]
    + waterCategory : HierarchicalWaterCategoryCodelist value [0..1]
    + protectedAreaType : ProtectedAreaTypeCodelist value [0..1]

    + implementationPeriod : YearRangeType [1]
    + implementationStatus : PlannedOngoingExecutedCancelledCodelist value [1]
}

class ExpendituresPerMeasurePerSector {
    + measureCode : wiselIdentifier [1]
    + expenditureDataAvailable : YesNoNotApplicable [1]

    + institutionalSector : sea2010SectorCodeList value [0..1]

    + totalCapitalExpenditure3rdCycle : NonNegativeNumberDecimalType [0..1]
    + totalCurrentExpenditure3rdCycle : NonNegativeNumberDecimalType [0..1]
    + totalCapitalExpenditure4thCycle : NonNegativeNumberDecimalType [0..1]
    + totalCurrentExpenditure4thCycle : NonNegativeNumberDecimalType [0..1]
    + millionUnitsOfNationalCurrency : CurrencyCode value [0..1]
}