classDiagram

class ExpenditurePerMeasurePerSector {
    + measureCode : wiselIdentifier [1]
    + expenditureDataAvailable : YesNoNotApplicable [1]
    + institutionalSector : sea2010SectorCodeList value [0..1]

    + totalCapitalExpenditure3rdCycle : NonNegativeNumberDecimalType [0..1]
    + totalCurrentExpenditure3rdCycle : NonNegativeNumberDecimalType [0..1]

    + totalCapitalExpenditure4thCycle : NonNegativeNumberDecimalType [0..1]
    + totalCurrentExpenditure4thCycle : NonNegativeNumberDecimalType [0..1]

    + millionUnitsOfNationalCurrency : CurrencyCode value [0..1]
}