---
config:
  class:
    hideEmptyMembersBox: true
  layout: dagre
  theme: neutral
---
classDiagram
direction TB

class Measure {
    + measureCode: wiseIdentifier
    + measureName: string
    + measureNameLanguage: Language
    + measureReference: referenceCode [0..1]

    + measureType: MeasureType 
    + mainLegalInstrument: LegalInstrument
    + mainKeyTypeOfMeasure: MainKeyTypeOfMeasure

    + mainPressureType: PressureType [0..1]
    + mainSubstanceType: SubstanceType [0..1]
    
    + msfdRelevance: YesNo
    + floodsRelevance: YesNo
    + natureRestorationRegulationRelevance: YesNo
    + draughtManagementPlanRelevance: YesNo
    + climateAdaptationPlanRelevance: YesNo

    + geographicalCoverage: WFDGeographicCoverage
    + euRBDCode: wiseIdentifier [0..n]
    + waterCategory: WaterCategory [0..1]
    + protectedAreaType: ProtectedAreaType [0..1]

    + implementationPeriod: range
    + implementationStatus: PlannedOngoingExecutedCancelled
}

class MeasureType{
    <<enumeration>>
    legislativeOrRegulatory
    administrativeOrGovernance
    physicalOrTechnical
    economicOrFinancial
    knowledgeOrPreparatory
}
class LegalInstrument{
    <<enumeration>>
    birdsDirective 
    bathingWaterDirective
    environmentalImpactAssessmentDirective
    environmentalQualityStandardsDirective2008 
    environmentalQualityStandardsDirective2013 
    floodsDirective
    groundwaterDirective 
    habitatsDirective 
    industrialEmissionsDirective
    marineStrategyFrameworkDirective 
    natureRestorationRegulation
    nitratesDirective 
    plantProtectionProductsRegulation
    recastDrinkingWaterDirective
    recastUrbanWasteWaterTreatmentDirective
    sevesoIIIDirective 
    sewageSludgeDirective 
    waterFrameworkDirective
    waterReuseRegulation
}
class MainKeyTypeOfMeasure{
    <<enumeration>>
}

class WFDGeographicCoverage{
    <<enumeration>>
    national
    riverBasinDistrict
    waterBody
    protectedArea    
}
class WaterCategory{
    <<enumeration>>
}
class ProtectedAreaType{
    <<enumeration>>
}

class PlannedOngoingExecutedCancelled{
    <<enumeration>>
    planned
    ongoing
    executed
    cancelled
}

Measure ..> MeasureType
Measure ..> LegalInstrument
Measure ..> MainKeyTypeOfMeasure
Measure ..> WFDGeographicCoverage
Measure ..> WaterCategory
Measure ..> ProtectedAreaType
Measure ..> PlannedOngoingExecutedCancelled

classDef default fill:white,stroke:#000;
classDef forFixing fill:white,stroke:#f00;