classDiagram

class RiverBasinManagementPlan {
    euRBMPCode : wideIdentifier [1]
    rbmpName : text (1000) [1]
    rbmpEstablishmentDate : Date [1]
    rbmpEndDate : Date [0..1]
    firstRBMPPublicationDate : Date [0..1]
    secondRBMPPublicationDate : Date [0..1]
    thirdRBMPPublicationDate : Date [0..1]
    rbmpStatus : YesNo [1]
    subPlans : YesNo [1]
    subPlanCoverageCodeList value [0..1]
    subPlanReference : DocumentReference [0..*]
    relatedPlans : DocumentReference [0..*]
    documentAvailability : YesNo [1]
    originalDataBasedEnvironment : OriginalDataBasedEnvironmentCodeList value [0..1]
    stakeholderGroups : StakeholderGroupCodeList value [0..*]
    coordinationRBMPWithFloodDirective : CoordinationCodeList value [1]
    coordinationRBMPWithMarineDirective : CoordinationCodeList value [1]
    coordinationRBMPWithNatureDirective : CoordinationCodeList value [1]
    integrationFloodDirective : YesNo [1]
    integrationMarineDirective : YesNo [1]
    coordinationRBMPWithNatureDirectiveApplicable : YesNo [1]
    coordinationRBMPWithNatureDirectiveApplicableText : text (1000) [0..1]
    coordinationRBMPReference : DocumentReference [0..*]
}

class Progress {
    euRBMPCode : wideIdentifier [1]
    plannedRBMPMeasuresStatus : PlannedOngoingExecutedCancelledCodeList value [1]
    preventedRBMPMeasure : YesNo [1]
    achievedRBMPMeasure : YesNo [1]
    achievedRBMPMeasureText : text (1000) [0..1]
    achievedRBMPMeasureTextReference : DocumentReference [0..*]
    achievedRBMPMeasureTextNote : text (1000) [0..1]
    achievedRBMPMeasureTextNoteReference : DocumentReference [0..*]
}

class TargetedQuestions {
    euRBMPCode : wideIdentifier [1]
    basicMeasuresAgriculture : BasicMeasuresChangeCodeList value [1]
    basicMeasuresIndustry : BasicMeasuresChangeCodeList value [1]
    basicMeasuresUrbanWasteWater : BasicMeasuresChangeCodeList value [1]
    basicMeasuresDrinkingWater : BasicMeasuresChangeCodeList value [1]
    basicMeasuresDiffusePollution : BasicMeasuresChangeCodeList value [1]
    basicMeasuresGroundwater : BasicMeasuresChangeCodeList value [1]
    basicMeasuresHydromorphological : BasicMeasuresChangeCodeList value [1]
    basicMeasuresOther : BasicMeasuresChangeCodeList value [1]
    supplementaryMeasuresAgriculture : SupplementaryMeasuresChangeCodeList value [1]
    supplementaryMeasuresIndustry : SupplementaryMeasuresChangeCodeList value [1]
    supplementaryMeasuresUrbanWasteWater : SupplementaryMeasuresChangeCodeList value [1]
    supplementaryMeasuresDrinkingWater : SupplementaryMeasuresChangeCodeList value [1]
    supplementaryMeasuresDiffusePollution : SupplementaryMeasuresChangeCodeList value [1]
    supplementaryMeasuresGroundwater : SupplementaryMeasuresChangeCodeList value [1]
    supplementaryMeasuresHydromorphological : SupplementaryMeasuresChangeCodeList value [1]
    supplementaryMeasuresOther : SupplementaryMeasuresChangeCodeList value [1]
    floodMeasures : YesNo [1]
    droughtMeasures : YesNo [1]
    protectedAreaMeasures : YesNo [1]
}

class Measure {
    measureCode : wideIdentifier [1]
    measureName : text (1000) [1]
    measureReference : DocumentReference [0..*]
    measureType : MeasureTypeCodeList value [1]
    mainPressureType : HierarchicalPressureCodeList value [1]
    mainKeyType : HierarchicalKeyCodeList value [1]
    mainSubstanceType : HierarchicalSubstanceCodeList value [1]
    mainFieldRelevance : YesNo [1]
    floodRelevance : YesNo [1]
    droughtRelevance : YesNo [1]
    protectedAreaRelevance : YesNo [1]
    geographicalCoverage : WFDGeographicalCoverageCodeList value [1]
    euRBMPCode : wideIdentifier [1]
    waterCategory : HierarchicalWaterCategoryCodeList value [1]
    protectedAreaType : ProtectedAreaTypeCodeList value [0..*]
    implementationPeriod : YearRangeType [0..1]
    implementationStatus : PlannedOngoingExecutedCancelledCodeList value [1]
}

class ExpendituresPerMeasurePerSector {
    measureCode : wideIdentifier [1]
    expenditureDataAvailable : YesNoNotApplicable [1]
    institutionalSector : isco2010SectionCodeList value [0..1]
    totalCapitalExpenditureBudgetCycle : NonNegativeNumberDecimalType [0..1]
    totalCurrentExpenditureBudgetCycle : NonNegativeNumberDecimalType [0..1]
    totalCapitalExpenditureDuringCycle : NonNegativeNumberDecimalType [0..1]
    totalCurrentExpenditureDuringCycle : NonNegativeNumberDecimalType [0..1]
    millionNationalCurrency : CurrencyCode value [0..1]
}