%%{init : {'theme' : 'neutral'}}%%
classDiagram
direction LR
namespace Codelist{
class MeasureType{
    <<enumeration>>
    }
class LegalInstrument{
    <<enumeration>>
    }
class HierarchicalPressureType{
    <<enumeration>>
    }
class HierarchicalSubstanceType{
    <<enumeration>>
    }
class WFDGeographicCoverage{
    <<enumeration>>
    national
    riverBasinDistrict
    waterBody
    protectedArea
    }
class HierarchicalWaterCategory{
    <<enumeration>>
    }    
class YesNo{
    <<enumeration>>
    yes
    no
    }    
}