---
config:
  class:
    hideEmptyMembersBox: true
  layout: dagre
  theme: neutral
---
classDiagram
direction LR

class dcMetadata {

«metadata»
+ title: string
+ creatorOrganisationName: string
+ creatorElectronicMailAddress: Email
+ description: string [0..1]
+ created: date [0..1]
+ language: Language [1..n]
+ license: Licence
+ rights: string [0..1]
+ rightsHolder: string [0..1]
+ licenseDocument: documentCode [0..n]

«manifest»
+ euRBDCode: wiseIdentifier
+ includesDescriptiveData: YesNo
}

class Reference {
  + referenceCode: wiseIdentifier
  + documentCode: documentCode
  + bookmark: string250
  + subject: string250 
}

class Document {
+ documentCode: wiseIdentifier
+ documentName: string250
+ hyperlink: URL [0..1]
+ documentFile: Attachment [0..1]
}

class Licence{
  <<enumeration>>
  CC0
  CC_BY_4_0
  exactMatch_CC_BY_4_0
  narrowMatch_CC_BY_4_0
}

Reference  ..> Document: documentCode
dcMetadata ..> Document: licenseDocument
dcMetadata ..> Licence: license
classDef default fill:white,stroke:#000;
classDef forFixing fill:white,stroke:#f00;