---
config:
  class:
    hideEmptyMembersBox: true
  layout: dagre
  theme: neutral
---
classDiagram
direction TB

class RiverBasinManagementPlan{
+ euRBDCode:  wiseIdentifier
+ rbmpName: string1000

+ rbmpTimetablePublicationDate: date 
+ rbmpProgrammePublicationDate: date 
+ rbmpConsultationPublicationDate: date 
+ rbmpInterimOverviewDate: date 
+ rbmpDraftVersionDate: date 
+ finalRBMPPublicationDate: date 

+ subPlans: YesNo
+ subPlansCoverage: SubPlansCoverage [0..1]
+ subPlansReference: referenceCode [0..n]

+ sea: YesNo
+ seaReference: referenceCode [0..n]

+ documentAvailability : YesNo

+ ongoingStakeholderInvolvement: OngoingStakeholderInvolvement [0..n]
+ stakeholderGroups: StakeholderGroups [0..n]

+ internationalCoordination: InternationalCoordination [0..n]
+ internationalCoordinationPublicParticipation: YesNo [0..1]
+ pomCoordinationArt5SWMI: Coordination
+ pomCoordinationIRBMPPoM: Coordination
+ pomCoordinationRoofReport: Coordination
+ pomCoordinationFinancial: Coordination

+ integrationFloodsDirective: YesNo
+ coordinationFloodsDirective: YesNoNotApplicable
+ coordinationMSFD: YesNoNotApplicable

+ coordinationNRRReference: referenceCode [1..n]
}

class Coordination{
    <<enumeration>>
    withEUMemberStates
    withCountriesOutsideEU
    both
    none
    }

class InternationalCoordination{
    <<enumeration>>
    internationalAgreement
    permanentCooperationBody
    internationalRBMP
    noFormalisedCoordination
    }

class OngoingStakeholderInvolvement{
    <<enumeration>>
    regularExhibitions
    establishmentOfAdvisoryGroups
    involvementInDrafting
    otherOutreachActivities
    formationOfAlliances
    other
    }

class SubPlansCoverage{
    <<enumeration>>
    agriculture
    chemicalIndustry
    chemicalPollution
    climateChange
    coastalErosion
    hydropower
    nutrientEnrichment
    ruralPlanning
    transport
    urbanPlanning
    waterScarcityAndDroughts
    other
    }

class StakeholderGroups{
    <<enumeration>>
    waterSupplyAndSanitation
    agricultureFarmers
    hydropowerAndEnergy
    navigationPorts
    fisheriesAndAquaculture
    industry
    ngosNatureProtection
    consumerGroups
    localAndRegionalAuthorities
    other    
    }

RiverBasinManagementPlan ..> SubPlansCoverage
RiverBasinManagementPlan ..> OngoingStakeholderInvolvement
RiverBasinManagementPlan ..> Coordination
RiverBasinManagementPlan ..> InternationalCoordination
RiverBasinManagementPlan ..> StakeholderGroups

classDef default fill:white,stroke:#000;
classDef forFixing fill:white,stroke:#f00;
