---
config:
  class:
    hideEmptyMembersBox: true
  layout: dagre
  theme: neutral
---
classDiagram
direction LR
namespace ReportingData{
class ExpenditurePerMeasurePerSector {
 + measureCode : wiselIdentifier
 + expenditureDataAvailable : YesNoNotApplicable
 + institutionalSector : SEA2010SectorCode [0..1]

 + totalCapitalExpenditure3rdCycle : NonNegativeNumberDecimalType [0..1]
 + totalCurrentExpenditure3rdCycle : NonNegativeNumberDecimalType [0..1]

 + totalCapitalExpenditure4thCycle : NonNegativeNumberDecimalType [0..1]
 + totalCurrentExpenditure4thCycle : NonNegativeNumberDecimalType [0..1]

 + millionUnitsOfNationalCurrency : CurrencyCode [0..1]
}
}
namespace Codelist{
class SEA2010SectorCode{
    <<enumeration>>
    }
class CurrencyCode{
    <<enumeration>>
    }
class YesNoNotApplicable{
    <<enumeration>>
    yes
    no
    notApplicable
    }
}


classDef default fill:white,stroke:#000;
classDef forFixing fill:white,stroke:#f00;