---
config:
  class:
    hideEmptyMembersBox: true
  layout: dagre
  theme: neutral
---
classDiagram
direction TB

class RiverBasinManagementPlan{
+ euRBDCode :  wiseIdentifier
+ rbmpName : String1000

+ rbmpTimetablePublicationDate : Date 
+ rbmpProgrammePublicationDate : Date 
+ rbmpConsultationPublicationDate : Date 
+ rbmpInterimOverviewDate : Date 
+ rbmpDraftVersionDate : Date 
+ finalRBMPPublicationDate : Date 

+ subPlans : YesNo
+ subPlansCoverage : SubPlansCoverage [0..1]
+ subPlansReference : referenceIdentifier [0..n]

+ sea : YesNo
+ seaReference : referenceIdentifier [0..n]

+ documentAvailability  : YesNo

+ ongoingStakeholderInvolvement : OngoingStakeholderInvolvement [0..n]
+ stakeholderGroups : StakeholderGroups [0..n]

+ internationalCoordination : InternationalCoordination [0..1]
+ internationalCoordinationPublicParticipation : YesNo [0..1]
+ pomCoordinationArt5SWMI : Coordination
+ pomCoordinationIRBMPPoM : Coordination
+ pomCoordinationRoofReport : Coordination
+ pomCoordinationFinancial : Coordination

+ integrationFloodsDirective : YesNo
+ coordinationFloodsDirective : YesNoNotApplicable
+ coordinationMSFD : YesNoNotApplicable

+ coordinationNRRReference : referenceIdentifier [1..n]
}

class SubPlansCoverage{
    <<enumeration>>
    agriculture
    chemicalIndustry
    chemicalPollution
    climateChange
    coastalErosion
    hydropower
    nutrientEnrichment
    ruralPlanning
    transport
    urbanPlanning
    waterScarcityAndDroughts
    other
    }
class OngoingStakeholderInvolvement{
    <<enumeration>>
    }
class Coordination{
    <<enumeration>>
    }

RiverBasinManagementPlan .. SubPlansCoverage

classDef default fill:white,stroke:#000;
classDef forFixing fill:white,stroke:#f00;
