---
config:
  class:
    hideEmptyMembersBox: true
  layout: dagre
  theme: neutral
---
classDiagram
direction TB

class RiverBasinManagementPlan{
+ euRBDCode :  wiseIdentifier
+ rbmpName : string1000

+ rbmpTimetablePublicationDate : date 
+ rbmpProgrammePublicationDate : date 
+ rbmpConsultationPublicationDate : date 
+ rbmpInterimOverviewDate : date 
+ rbmpDraftVersionDate : date 
+ finalRBMPPublicationDate : date 

+ subPlans : YesNo
+ subPlansCoverage : SubPlansCoverage [0..1]
+ subPlansReference : referenceCode [0..n]

+ sea : YesNo
+ seaReference : referenceCode [0..n]

+ documentAvailability  : YesNo

+ ongoingStakeholderInvolvement : OngoingStakeholderInvolvement [0..n]
+ stakeholderGroups : StakeholderGroups [0..n]

+ internationalCoordination : InternationalCoordination [0..1]
+ internationalCoordinationPublicParticipation : YesNo [0..1]
+ pomCoordinationArt5SWMI : Coordination
+ pomCoordinationIRBMPPoM : Coordination
+ pomCoordinationRoofReport : Coordination
+ pomCoordinationFinancial : Coordination

+ integrationFloodsDirective : YesNo
+ coordinationFloodsDirective : YesNoNotApplicable
+ coordinationMSFD : YesNoNotApplicable

+ coordinationNRRReference : referenceCode [1..n]
}

class SubPlansCoverage{
    <<enumeration>>
    agriculture
    chemicalIndustry
    chemicalPollution
    climateChange
    coastalErosion
    hydropower
    nutrientEnrichment
    ruralPlanning
    transport
    urbanPlanning
    waterScarcityAndDroughts
    other
    }
class OngoingStakeholderInvolvement{
    <<enumeration>>
    }
class Coordination{
    <<enumeration>>
    }
class StakeholderGroups{
    <<enumeration>>
    }

RiverBasinManagementPlan .. SubPlansCoverage
RiverBasinManagementPlan .. OngoingStakeholderInvolvement
RiverBasinManagementPlan .. Coordination
RiverBasinManagementPlan .. StakeholderGroups

classDef default fill:white,stroke:#000;
classDef forFixing fill:white,stroke:#f00;
