classDiagram
    direction TB

    class TargetedQ {
        <<XSDcomplexType>>
        + euRBDCode : wisedIdentifier [1]

        + basicMeasuresArt113c : BasicMeasuresChangesCodelist value [1]
        + basicMeasuresArt113d : BasicMeasuresArt113dCodelist value [1]
        + basicMeasuresArt113ePermit : BasicMeasuresCodelist value [1]
        + basicMeasuresArt113gRegister : BasicMeasuresCodelist value [1]
        + basicMeasuresArt113hThreshold : BasicMeasuresArt113hThresholdCodelist value [1]
        + basicMeasuresArt113eImpoundment : BasicMeasuresArt113iImpoundmentCodelist value [1]
        + basicMeasuresArt113f : BasicMeasuresChangesCodelist value [1]

        + basicMeasuresArt113gPermit : BasicMeasuresCodelist value [1]
        + basicMeasuresArt113gRegister : BasicMeasuresCodelist value [1]
        + basicMeasuresArt113gThreshold : BasicMeasuresArt113hThresholdCodelist value [1]
        + basicMeasuresArt113hRules : BasicMeasuresArt113hRulesCodelist value [1]

        + basicMeasuresArt113iPermit : YesNo [1]
        + basicMeasuresArt113iRegister : YesNo [1]
        + basicMeasuresArt113j : BasicMeasuresArt113jCodelist value [1]
        + basicMeasuresArt113k : YesNo [1]

        + waterReuseMeasure : YesNo [1]
        + ecologicalFlow : EcologicalFlowCodelist value [1]
        + ecologicalFlowImplementation : EcologicalFlowImplementationCodelist value [1]
        + climateChange : YesNo [1]
        + climateChangeGuidance : YesNo [1]
        + floodsDirective : YesNo [1]
        + structuralMeasures : YesNo [1]
        + msfdCoOrdination : YesNoNotRelevant [1]
        + msfdAssessment : YesNoNotRelevant [1]
    }

    class Costs {
        <<XSDcomplexType>>
        + costOfMeasuresScale20152021 : MSorRBD_Enum
        + costOfMeasurePeriod20152021 : YearRangeType
        + investmentCosts20152021 : NumberDecimalType
        + costExplanation20152021Reference : ReferenceType [1..*]

        + costOfMeasuresScale20212027 : MSorRBD_Enum
        + costOfMeasurePeriod20212027 : YearRangeType
        + investmentCosts20212027 : NumberDecimalType
        + annualCosts20212027 : NumberDecimalType
        + depreciation20212027 : YesNoCode_Enum
        + costExplanation20212027Reference : ReferenceType [1..*]

        + euFunds20152021 : NumberDecimalType
        + euFunds20212027 : NumberDecimalType
    }

    class Measure {
        <<XSDcomplexType>>
        + measureCode: String1000Type
        + measureName: String1000Type
        + measureType: MeasureType_Enum
        + basicMeasureType: BasicMeasureType_Enum [0..*]
        + msfdRelevance: YesNoNotRelevantUnclear_Union_Enum
        + measureReference: ReferenceType [1..*]
    }

    class KTM {
        <<XSDcomplexType>>
        + keyTypeMeasure: KTM_Enum
        + keyTypeMeasureOther: String1000Type [0..1]
    }

    class RBMPoM {
        <<XSDcomplexType>>
        + countryCode: CountryCode_Enum
        + euRBDCode: FeatureUniqueEUCodeType
    }

    TargetedQ <-- RBMPoM : +TargetedQ 1..1
    Costs <-- RBMPoM : +Costs 1..1
    Measure <-- RBMPoM : +Measure 1..*
    KTM <-- RBMPoM : +KTM 1..*