classDiagram

class TargetedQuestions {
     + euRBDCode : wisedIdentifier [1]

    + basicMeasuresArt113c : BasicMeasuresChangesCodelist value [1]
    + basicMeasuresArt113d : BasicMeasuresArt113dCodelist value [1]
    + basicMeasuresArt113ePermit : BasicMeasuresCodelist value [1]
    + basicMeasuresArt113gRegister : BasicMeasuresCodelist value [1]
    + basicMeasuresArt113hThreshold : BasicMeasuresArt113hThresholdCodelist value [1]
    + basicMeasuresArt113eImpoundment : BasicMeasuresArt113iImpoundmentCodelist value [1]
    + basicMeasuresArt113f : BasicMeasuresChangesCodelist value [1]

    + basicMeasuresArt113gPermit : BasicMeasuresCodelist value [1]
    + basicMeasuresArt113gRegister : BasicMeasuresCodelist value [1]
    + basicMeasuresArt113gThreshold : BasicMeasuresArt113hThresholdCodelist value [1]
    + basicMeasuresArt113hRules : BasicMeasuresArt113hRulesCodelist value [1]

    + basicMeasuresArt113iPermit : YesNo [1]
    + basicMeasuresArt113iRegister : YesNo [1]
    + basicMeasuresArt113j : BasicMeasuresArt113jCodelist value [1]
    + basicMeasuresArt113k : YesNo [1]

    + waterReuseMeasure : YesNo [1]
    + ecologicalFlow : EcologicalFlowCodelist value [1]
    + ecologicalFlowImplementation : EcologicalFlowImplementationCodelist value [1]
    + climateChange : YesNo [1]
    + climateChangeGuidance : YesNo [1]
    + floodsDirective : YesNo [1]
    + structuralMeasures : YesNo [1]
    + msfdCoOrdination : YesNoNotRelevant [1]
    + msfdAssessment : YesNoNotRelevant [1]
}