---
config:
  class:
    hideEmptyMembersBox: true
  layout: dagre
  theme: neutral
---
classDiagram
direction LR
namespace ReportingData{
class Measure {
 + measureCode : wiselIdentifier
 + measureName : String1000
 + measureReference : referenceIdentifier [0..1]

 + measureType : MeasureType 
 + mainLegalInstrument : LegalInstrument
 + mainKeyTypeOfMeasure : MainKeyTypeOfMeasure

 + mainPressureType : HierarchicalPressureType [0..1]
 + mainSubstanceType : HierarchicalSubstanceType [0..1]

 + msfdRelevance : YesNo
 + floodsRelevance : YesNo
 + natureRestorationRegulationRelevance : YesNo
 + draughtManagementPlanRelevance : YesNo
 + climateAdaptationPlanRelevance : YesNo

 + geographicalCoverage : WFDGeographicCoverage
 + euRBDCode : wiselIdentifier [0..n]
 + waterCategory : HierarchicalWaterCategory [0..1]
 + protectedAreaType : ProtectedAreaType [0..1]

 + implementationPeriod : YearRangeType
 + implementationStatus : PlannedOngoingExecutedCancelled
}
}
namespace Codelist{
    class MeasureType{
        <<enumeration>>
    }
    class LegalInstrument{
        <<enumeration>>
    }
    class MainKeyTypeOfMeasure{
        <<enumeration>>
    }
    class HierarchicalPressureType{
        <<enumeration>>
    }
    class HierarchicalSubstanceType{
        <<enumeration>>
    }
    class WFDGeographicCoverage{
        <<enumeration>>
    }
    class HierarchicalWaterCategory{
        <<enumeration>>
    }
    class ProtectedAreaType{
        <<enumeration>>
    }
    class YesNo{
        <<enumeration>>
        yes
        no
    }
    class PlannedOngoingExecutedCancelled{
        <<enumeration>>
        planned
        ongoing
        executed
        cancelled
    }
}

classDef default fill:white,stroke:#000;
classDef forFixing fill:white,stroke:#f00;