classDiagram
    direction TB

    class RBMP {
        <<XSComplexType>>
        <XSElement>
        + rbmpName: String1000Type
        + rbmpTimetablePublicationDate: DateType
        + rbmpProgrammePublicationDate: DateType
        + rbmpConsultationPublicationDate: DateType
        + rbmpInterimOverviewDate: DateType
        + rbmpDraftVersionDate: DateType
        + finalRBMPPublicationDate: DateType
        + subPlans: YesNoCode_Enum
        + subPlansCoverage: SubPlansCoverage_Enum [0..*]
        + subPlansCoverageOther: String1000Type [0..1]
        + subPlansReference: ReferenceType [0..*]
        + sea: YesNoCode_Enum
        + seaReference: ReferenceType [0..*]
        + publicConsultationInformation: PublicConsultationInformation_Enum [1..*]
        + publicConsultationInformationOther: String1000Type [0..1]
        + rbmpConsultation: RBMPConsultation_Enum [1..*]
        + rbmpConsultationOther: String1000Type [0..1]
        + documentProvision: DocumentProvision_Enum [1..*]
        + documentProvisionOther: String1000Type [0..1]
        + documentAvailability: YesNoCode_Enum
        + ongoingStakeholderInvolvement: OngoingStakeholderInvolvement_Enum [1..*]
        + ongoingStakeholderInvolvementOtherOutreach: String1000Type [0..1]
        + ongoingStakeholderInvolvementOther: String1000Type [0..1]
        + stakeholderGroups: StakeholderGroups_Enum [1..*]
        + stakeholderGroupsOther: String1000Type [0..1]
        + impactPublicParticipation: ImpactPublicParticipation_Enum [1..*]
        + impactPublicParticipationOther: String1000Type [0..1]
        + internationalCoOrdination: InternationalCoOrdination_Enum [1..*]
        + internationalCoOrdinationOther: String1000Type [0..1]
        + publicParticipationReference: ReferenceType [0..*]
        + consultationResponseReference: ReferenceType [0..*]
        + integrationFloodsDirective: YesNoCode_Enum
        + coOrdinationMSFD: YesNoNotApplicable_Union_Enum
        + coOrdinationReference: ReferenceType [0..*]
        + msfdCoordinationReference: ReferenceType [0..*]
    }

    class CoOrd {
        <<XSComplexType>>
        <XSElement>
        + pomCoOrdinationJointVision: Coord_Enum
        + pomCoOrdinationArt5SWMI: Coord_Enum
        + pomCoOrdinationIRBMPPoM: Coord_Enum
        + pomCoOrdinationRoofReport: Coord_Enum
        + pomCoOrdinationLinks: Coord_Enum [0..1]
        + pomCoOrdinationSectors: Coord_Enum [0..1]
        + pomCoOrdinationTransparency: Coord_Enum
        + pomCoOrdinationFinancial: Coord_Enum
        + iRBMPIssuesNutrient: YesNoCode_Enum [0..1]
        + iRBMPIssuesSediment: YesNoCode_Enum [0..1]
        + iRBMPIssuesChemical: YesNoCode_Enum [0..1]
        + iRBMPIssuesRiverContinuity: YesNoCode_Enum [0..1]
        + iRBMPIssuesOtherHydromorphological: YesNoCode_Enum [0..1]
        + iRBMPIssuesOther: String1000Type [0..1]
        + iRBMPReference: ReferenceType [0..*]
    }

    class Progress {
        <<XSComplexType>>
        <XSElement>
        + rbmpGeneralProgress: String4000Type [0..1]
        + financeSecured: YesNoCode_Enum
        + financeSecuredAgriculture: YesNoNotApplicable_Union_Enum
        + financeSecuredIndustry: YesNoNotApplicable_Union_Enum
        + financeSecuredTransport: YesNoNotApplicable_Union_Enum
        + financeSecuredHydropower: YesNoNotApplicable_Union_Enum
        + financeSecuredAquaculture: YesNoNotApplicable_Union_Enum
        + financeSecuredFloodProtection: YesNoNotApplicable_Union_Enum
        + newRegulation: YesNoCode_Enum
        + statusImplementationPoM: StatusImplementationPoM_Enum
        + improvementInStatusGeneral: ImprovementInStatusGeneral_Enum
        + improvementInStatusEcologicalSWB: ImprovementInStatusEcologicalSWB_Enum
        + improvementInStatusChemicalSWB: ImprovementInStatusChemicalSWB_Enum
        + improvementInStatusQuantitativeGWB: ImprovementInStatusQuantitativeGWB_Enum
        + improvementInStatusChemicalGWB: ImprovementInStatusChemicalGWB_Enum
        + obstaclesGovernance: YesNoCode_Enum
        + obstaclesDelays: YesNoCode_Enum
        + obstaclesLackOfFinance: YesNoCode_Enum
        + obstaclesLackOfMechanisms: YesNoCode_Enum
        + obstaclesLackOfMeasures: YesNoCode_Enum
        + obstaclesNotCostEffective: YesNoCode_Enum
        + obstaclesExtremeEvents: YesNoCode_Enum
        + obstaclesOther: String1000Type [0..1]
        + measuresFromPreviousProgrammeReference: ReferenceType [1..*]
    }

    class RBMPPoM {
        <<XSComplexType>>
    }

    RBMP <-- RBMPPoM : +RBMP 1..1
    CoOrd <-- RBMPPoM : +CoOrd 0..1
    Progress <-- RBMPPoM : +Progress 1..1
