---
config:
  class:
    hideEmptyMembersBox: true
  layout: dagre
  theme: neutral
---
classDiagram
direction TB

class Progress{
  + euRBDCode :  wiseIdentifier

  + previousRBMPMeasureStatus : PlannedOngoingExecutedCancelled
  + percentageInStatus : Percentage

  + obstaclesGovernance : YesNo
  + obstaclesDelays : YesNo
  + obstaclesLackOfFinance : YesNo
  + obstaclesLackOfMechanism : YesNo
  + obstaclesMeasureNotEffective : YesNo
  + obstaclesMeasureNotCostEffective : YesNo
  + obstaclesExtremeEvents : YesNo
}

class PlannedOngoingExecutedCancelled{
    <<enumeration>>
    planned
    ongoing
    executed
    cancelled
    }

Progress ..>  PlannedOngoingExecutedCancelled

classDef default fill:white,stroke:#000;
classDef forFixing fill:white,stroke:#f00;