---
config:
  class:
    hideEmptyMembersBox: true
  layout: dagre
  theme: neutral
---
classDiagram
direction LR

class dcMetadata {

«metadata»
+ title : string
+ creatorOrganisationName : string
+ creatorElectronicMailAddress : Email
+ description : string [0..1]
+ created : date [0..1]
+ language : Language [1..n]
+ license : URL
+ rights : string [0..1]
+ rightsHolder : string [0..1]
+ licenseDocument : documentCode [0..n]
+ metadataDocument : documentCode [0..n]

«manifest»
+ euRBDCode : wiseIdentifier
+ includesSpatialData : YesNo
+ includesMonitoringData : YesNo
}

class Reference {
  + referenceCode : wiseIdentifier
  + documentCode : Document
  + bookmark : string50
  + subject : string250 
}

class Document {
+ documentCode : wiseIdentifier
+ documentName : string250
+ hyperlink : URL [0..1]
+ documentFile : Attachment [0..1]
}

dcMetadata --> "0..n" Document : documentCode
Reference "0..n" --> Document : documentCode

classDef default fill:white,stroke:#000;
classDef forFixing fill:white,stroke:#f00;