%%{init: {'theme': 'neutral'}}%%
classDiagram
direction LR

class MonitoringProgrammes{
  + euRBDCode : wiseIdentifier
  + useWaterbaseForMonitoringData : YesNo
  + programmesReference : referenceIdentifier
  + investigativeMonitoringReference : referenceIdentifier
  + operationalMonitoringReference : referenceIdentifier
  + surveillanceMonitoringReference : referenceIdentifier
  + gwChemicalMonitoringReference : referenceIdentifier [0..1]
  + gwQuantitativeMonitoringReference : referenceIdentifier [0..1]
  + swChemicalMonitoringReference : referenceIdentifier [0..1]
  + swEcologicalMonitoringReference : referenceIdentifier [0..1]
}
