---
config:
  class:
    hideEmptyMembersBox: true
  layout: dagre
  theme: neutral
---
classDiagram
direction TB

class dcMetadata{<<documents>>}
class Reference{<<documents>>}
class Document {<<documents>>}
class Monitoring{}
class MonitoringPurpose{}
class MonitoringProgrammes{}
class MonitoringSite{<<spatial>>}

dcMetadata ..> Document
Reference ..> Document
MonitoringProgrammes ..> Reference 

MonitoringSite "1" -- "1..3" MonitoringPurpose 
Monitoring "0..n"-- "1" MonitoringSite 

classDef default fill:white,stroke:#000;
classDef forFixing fill:white,stroke:#f00;