%%{init: {'theme': 'neutral'}}%%
classDiagram
direction LR
namespace Codelist{
class ParameterCode{
  <<enumeration>>

  «quantitative monitoring»
  EEA_00-01-1 - Quantitative monitoring

  «biological quality elements»
  QE1-1 - Phytoplankton
  QE1-2 - Other aquatic flora
  QE1-2-1 - Macroalgae
  QE1-2-2 - Angiosperms
  QE1-2-3 - Macrophytes
  QE1-2-4 - Phytobenthos
  QE1-3 - Benthic invertebrates
  QE1-4 - Fish
  QE1-5 - Other species

  «hydromorphological quality elements»
  QE2-1 - Hydrological or tidal regime
  QE2-2 - River continuity conditions
  QE2-3 - Morphological conditions

  «CAS codes and EEA codes under WISE-6»
  ...
}

class ChemicalMatrixType{
    <<enumeration>>
    water
    biota
    sediment
    }

class ChemicalPurpose{
    <<enumeration>>
    status
    trend
    both
    }   

class MonitoringFrequency{
    <<enumeration>>
    continuousSampling
    oneSamplePerMonitoringYear
    from2To6SamplesPerMonitoringYear
    from7To12SamplesPerMonitoringYear
    from13To24SamplesPerMonitoringYear
    moreThan24SamplesPerMonitoringYear
    unknown
    }   

class MonitoringCycle{
    <<enumeration>>
    onceEvery1Year
    onceEvery2Years
    onceEvery3Years
    onceEvery4Years
    onceEvery5Years
    onceEvery6Years
    onceEvery2RBMPs
    onceEvery3RBMPs
    unknown
    }   

class MonitoringPurpose{
    <<enumeration>>
    investigativeMonitoring
    operationalMonitoring
    surveillanceMonitoring
    }       
}