---
config:
  class:
    hideEmptyMembersBox: true
  layout: dagre
  theme: neutral
---
classDiagram
direction LR
namespace Documents {
    class dcMetadata {
    }
    class Reference {
    }
    class Document {
    }
}
namespace Descriptive {
    class Monitoring{
}
    class MonitoringProgrammes{
}
}
namespace Spatial {
    class MonitoringSite{
}
}