---
config:
  class:
    hideEmptyMembersBox: true
  layout: dagre
  theme: neutral
---
classDiagram
direction LR

class MonitoringProgrammes{
  + euRBDCode: wiseIdentifier
  + useWaterbaseForMonitoringData: YesNo
  + programmesReference: referenceCode
  + investigativeMonitoringReference: referenceCode
  + operationalMonitoringReference: referenceCode
  + surveillanceMonitoringReference: referenceCode
  + gwChemicalMonitoringReference: referenceCode [0..1]
  + gwQuantitativeMonitoringReference: referenceCode [0..1]
  + swChemicalMonitoringReference: referenceCode [0..1]
  + swEcologicalMonitoringReference: referenceCode [0..1]
}

classDef default fill:white,stroke:#000;
classDef forFixing fill:white,stroke:#f00;