---
config:
  class:
    hideEmptyMembersBox: true
  layout: dagre
  theme: neutral
---
classDiagram
direction TB

class MonitoringPurpose{
  + euMonitoringSiteCode: wiseIdentifier
  + monitoringPurpose: WFDMonitoringPurpose [1..3]
}

class WFDMonitoringPurpose{
    <<enumeration>>
    investigativeMonitoring
    operationalMonitoring
    surveillanceMonitoring
    }     

MonitoringPurpose ..> WFDMonitoringPurpose

classDef default fill:white,stroke:#000;
classDef forFixing fill:white,stroke:#f00;