---
config:
  class:
    hideEmptyMembersBox: true
  layout: dagre
  theme: neutral
---
classDiagram
direction LR
class MonitoringPurpose{
  + euMonitoringSiteCode : wiseIdentifier
  + monitoringPurpose : MonitoringPurpose
}



