%%{init: {'theme': 'neutral'}}%%

flowchart LR

%% Groundwater Quantitative Status Exemptions
title@{ shape: braces, label: "Groundwater Quantitative Status Exemptions" }

%% Defining the nodes
		
initial([start])
final([end])

%% duplicate nodeS for just for flowchart readability
hasNoApplicableExemption_1("no exemption \n applicable"):::stateRed
hasNoApplicableExemption_2("no exemption \n required"):::stateBlue
hasNoApplicableExemption_3("no exemption \n applicable"):::stateRed

hasExemption44n("Article 4(4) \n Extension of deadline \n (natural conditions)"):::state
hasExemption45("Article 4(5) \n Less stringent objectives"):::state
hasExemption46("Article 4(6) \n Temporary deterioration"):::state
hasExemption47("Article 4(7) \n New modification/project"):::state

%% Defining the decisions

isQuantitativeStatusIn2027{"Quantitative \n Status \n in 2027?"}
isDeteriorationExpected{"Deterioration expected \n beyond 2027?"}
isDeteriorationObserved{"Deterioration observed \n in 2027 or earlier?"}
isGoodStatusAchievable{"Is good status \n achievable?"}
isDelayDueToNaturalConditions{"Delay due to \n natural conditions?"}

%% Flow to TERMINATORS

initial --> isQuantitativeStatusIn2027
hasNoApplicableExemption_1 --> final
hasNoApplicableExemption_2 --> final
hasNoApplicableExemption_3 --> final
hasExemption47 --> final 
hasExemption46 --> final 
hasExemption45 --> final 
hasExemption44n --> final 

%% THE IMPORTANT PART STARTS HERE

    %% NO EXEMPTION POSSIBLE - If the status is unknown, then exemptions cannot be reported
    isQuantitativeStatusIn2027 ==>|unknown|hasNoApplicableExemption_1

    %% NO EXEMPTION NEEDED - if the status is not failing and no deterioration is expected, then no exemption is needed
    isQuantitativeStatusIn2027 ==>|not failing|isDeteriorationExpected
    isDeteriorationExpected ==>|no|hasNoApplicableExemption_2

    %% ARTICLE 4(7) - DETERIORATION DUE TO NEW MODIFICATION OR PROJECT
    isDeteriorationExpected ==>|"yes \n [new modification \n OR sustainable human development]"|hasExemption47
        
    %% ARTICLE 4(6) - DETERIORATION DUE TO ACCIDENTS OR FORCE MAJEURE OR NATURAL CAUSES
    isQuantitativeStatusIn2027 ==>|failing|isDeteriorationObserved
    isDeteriorationObserved ==>|"yes \n [new modification \n OR sustainable human development]"|hasExemption47
    isDeteriorationObserved ==>|"yes \n [accidents  \n OR force majeure  \n OR natural causes]"|hasExemption46
    isDeteriorationObserved ==>|no|isGoodStatusAchievable

    %% ARTICLE 4(5) - LESS STRINGENT OBJECTIVES
    isGoodStatusAchievable ==>|no|hasExemption45

    %% ARTICLE 4(4) EXTENSION OF DEADLINE - NATURAL CONDITIONS
    isGoodStatusAchievable ==>|yes|isDelayDueToNaturalConditions
            
    isDelayDueToNaturalConditions ==>|yes|hasExemption44n
            
    %% ARTICLE 4(5) EXTENSION OF DEADLINE - FEASIBILITY OR COST - NO EXEMPTION POSSIBLE
    isDelayDueToNaturalConditions ==>|no|hasNoApplicableExemption_3

%% styling
classDef state stroke-width:4px,fill:transparent
classDef stateRed stroke:red,fill:transparent
classDef stateBlue stroke:blue,fill:transparent
