---
config:
  class:
    hideEmptyMembersBox: true
  layout: dagre
  theme: neutral
---
classDiagram
direction LR
class CompetentAuthority {
  + euCACode: wiseIdentifier
  + competentAuthorityName: string100
  + competentAuthorityNameNL: string100
  + competentAuthorityNameNLLanguage: Language
  + acronym: string100 [0..1]
  + street: string100
  + city: string100
  + country: string100
  + postCode: string50
  + url: URL
}
class RiverBasinDistrictCompetentAuthority {
  + euRBDCode: wiseIdentifier
  + euCACode: wiseIdentifier
  + roleCode: Role [1..*]
}

CompetentAuthority "1" -- "1..*" RiverBasinDistrictCompetentAuthority

classDef default fill:white,stroke:#000;
classDef forFixing fill:white,stroke:#f00;
