---
config:
  class:
    hideEmptyMembersBox: true
  layout: dagre
  theme: neutral
---
classDiagram
direction LR
namespace DescriptiveData {
class CompetentAuthority {
+ euCACode : wiseIdentifier
+ competentAuthorityName : varchar100
+ competentAuthorityNameNL : nvarchar100
+ competentAuthorityNameNLLanguage : Language
+ acronym : nvarchar100 [0..1]
+ street : nvarchar100
+ city : nvarchar100
+ country : nvarchar100
+ postCode : nvarchar50 [0..1]
+ url : URL
}
class RiverBasinDistrictCompetentAuthority {
+ euRBDCode: wiseIdentifier
+ euCACode: wiseIdentifier
+ roleCode: Role [1..*]
}
}
CompetentAuthority --> "1..*" RiverBasinDistrictCompetentAuthority