---
config:
  class:
    hideEmptyMembersBox: true
  layout: dagre
  theme: neutral
---
classDiagram
direction LR
namespace Codelist{
class Role{
<<enumeration>>
pressureAndImpactAnalysis
economicAnalysis
monitoringOfSurfaceWater
monitoringOfGroundwater
assessmentOfStatusOfSurfaceWater
assessmentOfStatusOfGroundwater
preparationOfRBMP
preparationOfProgrammeOfMeasures
implementationOfMeasures
publicParticipation
enforcementOfRegulations
coordinationOfImplementation
reportingToTheEuropeanCommission
}
}