%%{init: {'theme': 'default'}}%%
classDiagram
direction TB

    class RiverBasinDistrict["«FeatureType»
    RiverBasinDistrict"] {
        +geometry: GM_MultiSurface
        +inspireIdLocalId: String254LeadingLetterOrNum
        +inspireIdNamespace: String254LeadingLetterOrNum
        +inspireIdVersionId: String25Type [0..1]
        +thematicIdIdentifier: FeatureUniqueEUCodeType
        +thematicIdIdentifierScheme: IdentifierScheme
        +beginLifespanVersion: WiseDateTimeType [0..1]
        +endLifespanVersion: WiseDateTimeType [0..1]
        +predecessorsIdentifier: String254LeadingLetterOrNum [0..1]
        +predecessorsIdentifierScheme: IdentifierScheme [0..1]
        +successorsIdentifier: String254LeadingLetterOrNum [0..1]
        +successorsIdentifierScheme: IdentifierScheme [0..1]
        +wiseEvolutionType: WiseEvolutionTypeValue
        +nameTextInternational: String254Latin
        +nameText: String254Type
        +nameLanguage: WiseLanguageCode_Enum
        +designationPeriodBegin: WiseDateTimeType
        +designationPeriodEnd: WiseDateTimeType [0..1]
        +zoneType: ZoneTypeCode
        +legalBasisName: String254LeadingLetterOrNum [0..1]
        +legalBasisLink: URLType [0..1]
        +legalBasisLevel: LegislationLevelValue [0..1]
        +relatedZoneTransboundaryIdentifier: String254LeadingLetterOrNum [0..1]
        +relatedZoneTransboundaryIdentifierScheme: IdentifierScheme [0..1]
        +sizeValue: PositiveDecimalType [0..1]
        +sizeUom: UomSize [0..1]
        +link: URLType [0..1]
    }

    class FeatureCollectionRBD["«FeatureType»
    FeatureCollection"] {
    }

    class SubUnit["«FeatureType»
    SubUnit"] {
        +geometry: GM_MultiSurface
        +inspireIdLocalId: String254LeadingLetterOrNum
        +inspireIdNamespace: String254LeadingLetterOrNum
        +inspireIdVersionId: String25Type [0..1]
        +thematicIdIdentifier: FeatureUniqueEUCodeType
        +thematicIdIdentifierScheme: IdentifierScheme
        +beginLifespanVersion: WiseDateTimeType [0..1]
        +endLifespanVersion: WiseDateTimeType [0..1]
        +predecessorsIdentifier: String254LeadingLetterOrNum [0..1]
        +predecessorsIdentifierScheme: IdentifierScheme [0..1]
        +successorsIdentifier: String254LeadingLetterOrNum [0..1]
        +successorsIdentifierScheme: IdentifierScheme [0..1]
        +wiseEvolutionType: WiseEvolutionTypeValue
        +nameTextInternational: String254Latin
        +nameText: String254Type
        +nameLanguage: WiseLanguageCode_Enum
        +designationPeriodBegin: WiseDateTimeType
        +designationPeriodEnd: WiseDateTimeType [0..1]
        +zoneType: ZoneTypeCode
        +specialisedZoneType: SpecialisedZoneTypeCode
        +legalBasisName: String254LeadingLetterOrNum [0..1]
        +legalBasisLink: URLType [0..1]
        +legalBasisLevel: LegislationLevelValue [0..1]
        +relatedZoneIdentifier: FeatureUniqueEUCodeType
        +relatedZoneIdentifierScheme: IdentifierScheme
        +relatedZoneTransboundaryIdentifier: String254LeadingLetterOrNum [0..1]
        +relatedZoneTransboundaryIdentifierScheme: IdentifierScheme [0..1]
        +sizeValue: PositiveDecimalType [0..1]
        +sizeUom: UomSize [0..1]
        +link: URLType [0..1]
    }

    class FeatureCollectionSU["«FeatureType»
    FeatureCollection"] {
    }

    RiverBasinDistrict "1..*" <-- FeatureCollectionRBD : +featureMember
    SubUnit "1..*" <-- FeatureCollectionSU : +featureMember