%%{init: {'theme': 'default'}}%%
classDiagram
direction TB

    class CompetentAuthority["«XSDcomplexType»
    CompetentAuthority"] {
        «XSDelement»
        +euCACode: FeatureUniqueEUCodeType
        +competentAuthorityName: String250Type
        +competentAuthorityNameNL: String250Type
        +competentAuthorityNameNLLanguage: LanguageCode_Enum
        +linkToCompetentAuthority: String1000Type
        +acronym: String100Type [0..1]
        +street: String100Type [0..1]
        +city: String100Type [0..1]
        +cityNL: String100Type [0..1]
        +country: String100Type [0..1]
        +postcode: String100Type [0..1]
        +mainRole: Roles_Enum [1..*]
        +otherRole: Roles_Enum [0..*]
    }

    class RBD["«XSDcomplexType»
    RBD"] {
        «XSDelement»
        +euRBDCode: FeatureUniqueEUCodeType
        +euSubUnitCode: FeatureUniqueEUCodeType [0..*]
        +internationalRBD: YesNoCode_Enum
        +internationalRBDName: String250Type [0..1]
        +primeCompetentAuthority: FeatureUniqueEUCodeType [1..*]
        +otherCompetentAuthority: FeatureUniqueEUCodeType [0..*]
        +subUnitsDefined: YesNoCode_Enum
    }

    class dcMetadata["WFDCommon_2022::dcMetadata"] {
        «XSDelement»
        +created: WiseDateTime [0..1]
        +creatorElectronicMailAddress: EmailType
        +creatorOrganisationName: String4000Type
        +description: String4000Type [0..1]
        +language: LanguageCode_Enum
        +license: URLType
        +title: String4000Type [0..1]
        +rights: String4000Type [0..1]
        +rightsHolder: String4000Type [0..1]
    }

    class RBDSUCA["«XSDcomplexType»
    RBDSUCA"] {
        «XSDelement»
        +countryCode: CountryCode_Enum
    }

  
    class RBDSUCATop["«XSDtopLev...
    RBDSUCA"] {
    }

    CompetentAuthority "1..*" <-- RBDSUCA : +CompetentAuthority
    RBD "1..*" <-- RBDSUCA : +RBD
    RBDSUCA "1..1" --> dcMetadata
    RBDSUCATop --|> RBDSUCA
    