---
config:
  class:
    hideEmptyMembersBox: true
  layout: dagre
  theme: neutral
---
classDiagram
direction LR
class MonitoringSite{
  + geometry_point : geometry_multipoint
  + inspireIdLocalId : String254
  + inspireIdNamespace : String254 
  + inspireIdVersionId : String25 [0..1]
  + thematicIdIdentifier : wiseIdentifier
  + thematicIdIdentifierScheme : IdentifierScheme
  + beginLifespanVersion : Date [0..1]
  + endLifespanVersion : Date [0..1]
  + supersedesIdentifier : String500 [0..1]
  + supersedesIdentifierScheme : IdentifierScheme [0..1]
  + supersededByIdentifier : String500 [0..1]
  + supersededByIdentifierScheme : IdentifierScheme [0..1]
  + wiseEvolutionType : WiseEvolutionType
  + nameTextInternational : String254
  + nameText : String254
  + nameLanguage : Language
  + operationalActivityPeriodBegin : Date 
  + operationalActivityPeriodEnd : Date [0..1]
  + featureOfInterestIdentifier : wiseIdentifier
  + featureOfInterestIdentifierScheme : IdentifierScheme
  + mediaMonitoredBiota : YesNo
  + mediaMonitoredWater : YesNo
  + mediaMonitoredSediment : YesNo
  + purpose : String254 [0..*]
  + confidentialityStatus : ConfidentialityStatus
  + link : URL [0..1]
}