---
config:
  class:
    hideEmptyMembersBox: true
  layout: dagre
  theme: neutral
---
classDiagram
direction LR
class RiverBasinDistrict {
  + geometry_polygon: MultiPolygon
  + inspireIdLocalId: string254
  + inspireIdNamespace: string254
  + inspireIdVersionId: string25 [0..1]
  + thematicIdIdentifier: wiseIdentifier
  + thematicIdIdentifierScheme: IdentifierScheme
  + beginLifespanVersion: date [0..1]
  + endLifespanVersion: date [0..1]
  + predecessorsIdentifier: wiseIdentifier [0..n]
  + predecessorsIdentifierScheme: IdentifierScheme [0..1]
  + successorsIdentifier: wiseIdentifier [0..n]
  + successorsIdentifierScheme: IdentifierScheme [0..1]
  + wiseEvolutionType: WiseEvolutionType
  + nameTextInternational: string254
  + nameText: string254
  + nameLanguage: Language
  + designationPeriodBegin: date
  + designationPeriodEnd: date [0..1]
  + zoneType: ZoneType
  + specialisedZoneType: SpecialisedZoneType
  + legalBasisName: string254 [0..1]
  + legalBasisLink: URL [0..1]
  + legalBasisLevel: LegislationLevelValue [0..1]
  + link: URL [0..1]
}

classDef default fill:white,stroke:#000;
classDef forFixing fill:white,stroke:#f00;