---
config:
  class:
    hideEmptyMembersBox: true
  layout: dagre
  theme: neutral
---
classDiagram
direction TB

class SWType{
    + swTypeIdentifier: wiseIdentifier
    + surfaceWaterBodyCategory: WaterBodyCategory
    + naturalAWBHMWB: NaturalAWBHMWB
    + swIntercalibrationType: IntercalibrationType [1..n]
    + swTypeCode: string100
    + swTypeDescription: string
    + swTypeDescriptionLanguage: Language

    + swTypeReference: referenceCode [0..n]

    «quality-elements»
    + QE1_1:     AllSomeInapplicableNotUsed
    + QE1_2_1:   AllSomeInapplicableNotUsed
    + QE1_2_2:   AllSomeInapplicableNotUsed
    + QE1_2_3:   AllSomeInapplicableNotUsed
    + QE1_2_4:   AllSomeInapplicableNotUsed
    + QE1_3:     AllSomeInapplicableNotUsed
    + QE1_4:     AllSomeInapplicableNotUsed
    + QE2_1:     AllSomeNotUsed
    + QE2_2:     AllSomeNotUsed
    + QE2_3:     AllSomeNotUsed
    + QE3_1_1:   AllSomeNotUsed
    + QE3_1_2:   AllSomeNotUsed
    + QE3_1_3:   AllSomeNotUsed
    + QE3_1_4:   AllSomeNotUsed
    + QE3_1_5:   AllSomeNotUsed
    + QE3_1_6_1: AllSomeNotUsed
    + QE3_1_6_2: AllSomeNotUsed
}

class SWQualityElement["SurfaceWaterDataset::SWQualityElement"]:::partial{ 
}

class SWPollutant["SurfaceWaterDataset::SWPollutant"]:::partial{ 
}

SWQualityElement ..> QE1Classification: qeClassificationIdentifier
SWQualityElement ..> QE3Classification: qeClassificationIdentifier


QE1Classification -- "0..n" QEClassification_SWType
QE3Classification -- "0..n" QEClassification_SWType   
QEClassification_SWType "0..n" -- SWType 


SWPollutant ..> SWThresholdValue: swThresholdIdentifier
SWThresholdValue -- "0..n" SWThreshold_SWType 
SWThreshold_SWType "0..n" -- SWType
SWType "1" -- "1..n" SWNaturalBackgroundLevel

classDef default fill:white,stroke:#000;
classDef forFixing fill:white,stroke:#f00;
classDef partial fill:lavender,stroke:#000;