---
config:
  class:
    hideEmptyMembersBox: true
  layout: dagre
  theme: neutral
---
classDiagram
direction LR

class SWThresholdValue{
+ swThresholdIdentifier : wiseIdentifier
+ parameterCode : Parameter
+ eqsStandardType : EnvironmentalQualityStandard
+ chemicalMatrix : ChemicalMatrixType 

+ thresholdValueRange : range [0..1]
+ thresholdValueUnit : UnitOfMeasure [0..1]
+ naturalBackgroundLevelSet : YesNoNotApplicable

«compliance-with-criteria»
+ analyticalMethod : YesNo
+ analyticalMethodBAT : YesNoNotApplicable

«reference»
+ swThresholdReference : referenceCode [0..n]

«for-data-quality-control-purposes»
+ applicableToRW : YesNo
+ applicableToLW : YesNo
+ applicableToTW : YesNo
+ applicableToCW : YesNo
+ applicableToTeW : YesNo
}

classDef default fill:white,stroke:#000;
classDef forFixing fill:white,stroke:#f00;
classDef partial fill:lightyellow,stroke:#000;