---
config:
  class:
    hideEmptyMembersBox: true
  layout: dagre
  theme: neutral
---
classDiagram
direction LR

class QE3Classification{
+ qeClassificationIdentifier : wiseIdentifier
+ qeCode : PhysicoChemicalQualityElement
+ parameterCode : Parameter
+ parameterUnit : UnitOfMeasure
+ eqsStandardType : EnvironmentalQualityStandard
+ classHighOrMax : range
+ classGood : range
+ classModerate : range

«scope-and-references»
+ naturalBackgroundLevelSet : YesNoNotApplicable
+ swTypeIdentifier : wiseIdentifier
+ qeClassificationReference : referenceCode [0..n]
}


classDef default fill:white,stroke:#000;
classDef forFixing fill:white,stroke:#f00;
classDef partial fill:lightyellow,stroke:#000;