---
config:
  class:
    hideEmptyMembersBox: true
  layout: dagre
  theme: neutral
---
classDiagram
direction TB

class SWType {
+ swTypeIdentifier : wiseIdentifier
}

class SWQualityElement["SurfaceWaterDataset::SWQualityElement"]:::otherDataset{
+ euSurfaceWaterBodyCode : wiseIdentifier
+ qeCode : QualityElement
+ qeClassificationIdentifier : wiseIdentifier
}

class BQEMethod{
+ bqeMethodIdentifier : wiseIdentifier
+ bqeCode : BiologicalQualityElement
}

class QE1Classification{
+ qeClassificationIdentifier : wiseIdentifier
+ qeCode : BiologicalQualityElement
+ bqeMethodIdentifier : wiseIdentifier 
}

class SWType_QEClassification{
+ swTypeIdentifier : wiseIdentifier
+ qeClassificationIdentifier
}

SWQualityElement ..> QE1Classification : qeClassificationIdentifier

BQEMethod "1" -- "1..n" QE1Classification 
QE1Classification "1" -- "0..n" SWType_QEClassification
SWType_QEClassification "0..n" -- "1" SWType 

classDef default fill:white,stroke:#000;
classDef forFixing fill:white,stroke:#f00;
classDef otherDataset fill:lavender,stroke:#000;
