---
config:
  class:
    hideEmptyMembersBox: true
  layout: dagre
  theme: neutral
---
classDiagram
direction TB

class SWType:::partial{
+ swTypeIdentifier : wiseIdentifier
}

class SWQualityElement["SurfaceWaterDataset::SWQualityElement"]:::partial{
+ euSurfaceWaterBodyCode : wiseIdentifier
+ qeCode : QualityElement
+ qeClassificationIdentifier : wiseIdentifier [0..n]
}

class QE3Classification{
+ qeClassificationIdentifier : wiseIdentifier
+ qeCode : PhysicoChemicalQualityElement
+ parameterCode : Parameter
+ parameterUnit : UnitOfMeasure
}

class SWType_QEClassification{
+ swTypeIdentifier : wiseIdentifier
+ qeClassificationIdentifier
}

class SWNaturalBackgroundLevel{
+ swTypeIdentifier : wiseIdentifier
+ parameterCode : ParameterCode
+ parameterValue : range  
+ parameterUnit : UnitOfMeasure
}

SWQualityElement "1..n" .. QE3Classification : qeClassificationIdentifier
QE3Classification -- "1..n" SWType_QEClassification : qeClassificationIdentifier
SWType_QEClassification "1..n" -- SWType : swTypeIdentifier
SWType -- "1..n" SWNaturalBackgroundLevel

classDef default fill:white,stroke:#000;
classDef forFixing fill:white,stroke:#f00;
classDef partial fill:lightyellow,stroke:#000;