---
config:
  class:
    hideEmptyMembersBox: true
  layout: dagre
  theme: neutral
---
classDiagram
direction LR
namespace Documents {
class dcMetadata {
+ euRBDCode : wiseIdentifier
+ title : String4000
+ creatorOrganisationName : String4000
+ creatorElectronicMailAddress : Email
+ description : String4000 [0..1]
+ created : Date [0..1]
+ language : Language [1..n]
+ license : URL
+ rights : String4000 [0..1]
+ rightsHolder : String4000 [0..1]
+ licenseDocument : documentCode [0..*]
+ metadataDocument : documentCode [0..*]
+ includesSpatialData : YesNo
}

class Reference {
  + referenceCode : wiseIdentifier
  + documentCode : Document
  + bookmark : String50
  + subject : String250 
}

class Document {
+ documentCode : wiseIdentifier
+ documentName : String250
+ hyperlink : URL [0..1]
+ documentFile : Attachment [0..1]
}
}
dcMetadata --> "0..*" Document : documentCode
Reference "0..*" --> Document : documentCode