---
config:
  class:
    hideEmptyMembersBox: true
  layout: dagre
  theme: neutral
---
classDiagram
direction TB

class SWType:::partial{
+ swTypeIdentifier: wiseIdentifier
}

class SWQualityElement["SurfaceWaterDataset::SWQualityElement"]:::otherDataset{
+ euSurfaceWaterBodyCode: wiseIdentifier
+ qeCode: QualityElement
+ qeClassificationIdentifier: wiseIdentifier
}

class QE2Classification{
+ qeClassificationIdentifier: wiseIdentifier
+ qeCode: HydroMorphologicalQualityElement

}

class QEClassification_SWType{
+ qeClassificationIdentifier: wiseIdentifier
+ swTypeIdentifier: wiseIdentifier
+ swIntercalibrationType: IntercalibrationType [1..n]
}


SWQualityElement ..> QE2Classification
QE2Classification "1" -- "0..n" QEClassification_SWType
QEClassification_SWType "0..n" -- "1" SWType

classDef default fill:white,stroke:#000;
classDef forFixing fill:white,stroke:#f00;
classDef otherDataset fill:lavender,stroke:#000;