---
config:
  class:
    hideEmptyMembersBox: true
  layout: dagre
  theme: neutral
---
classDiagram
direction LR

class SWType {
    + swTypeIdentifier : wiseIdentifier
    + swTypeDescription : string
    + swTypeCategory : WaterBodyCategory
    + swIntercalibrationType : IntercalibrationType
}

class SWTypeReferenceCondition {
    + swTypeIdentifier : wiseIdentifier
    + qeCode: QualityElement
    + swTypeReferenceCondition : string
}

class BQEMethod{
+ bewMethodIdentifier : wiseIdentifier
+ bqeMethodName : string
+ bqeCode : BiologicalQualityElement

«sensitivity»
+ bqeSensitivityImpactNutrients : YesNo
+ bqeSensitivityImpactOrganic : YesNo
+ bqeSensitivityImpactChemical : YesNo
+ bqeSensitivityImpactSaline : YesNo
+ bqeSensitivityImpactAcidification : YesNo
+ bqeSensitivityImpactTemperature : YesNo
+ bqeSensitivityImpactHydrological : YesNo
+ bqeSensitivityImpactMorphological : YesNo

«reference»
+ bqeMethodReference : referenceCode [0..n]

«for-data-quality-control-purposes»
+ applicableToRW : YesNo
+ applicableToLW : YesNo
+ applicableToTW : YesNo
+ applicableToCW : YesNo
}


class SWPollutant ["SurfaceWaterDataset::SWPollutant"]:::otherDataset{
+ euSurfaceWaterBodyCode
+ swPollutantCode
+ swThresholdIdentifier [1..3]
}

class SWThresholdValue{
+ swThresholdIdentifier : wiseIdentifier
+ parameterCode : Parameter
+ eqsStandardType : EnvironmentalQualityStandard
+ chemicalMatrix : ChemicalMatrixType 
+ thresholdValueDefined : YesNo
+ thresholdValueRange : range [0..1]
+ thresholdValueUnit : UnitOfMeasure [0..1]
+ naturalBackgroundLevelSet : YesNoNotApplicable
+ nblValueRange : range  [0..1] 

«compliance-with-criteria»
+ analyticalMethod : YesNo
+ analyticalMethodBAT : YesNoNotApplicable

«reference»
+ swThresholdReference : referenceCode [0..n]

«for-data-quality-control-purposes»
+ applicableToRW : YesNo
+ applicableToLW : YesNo
+ applicableToTW : YesNo
+ applicableToCW : YesNo
+ applicableToTeW : YesNo
}

class SWThresholdSWType{
+ swThresholdIdentifier : wiseIdentifier
+ swTypeIdentifier : wiseIdentifier
}


SWPollutant "1..n" .. SWThresholdValue : swThresholdIdentifier
SWThresholdValue .. "0..n" SWThresholdSWType : swThresholdIdentifier
SWThresholdSWType "0..n" .. SWType : swTypeIdentifier

SWTypeReferenceCondition "1..19" -- "1" SWType

classDef default fill:white,stroke:#000;
classDef forFixing fill:white,stroke:#f00;
classDef otherDataset fill:lightyellow,stroke:#000;