---
config:
  class:
    hideEmptyMembersBox: true
  layout: dagre
  theme: neutral
---
classDiagram
direction TB

class SurfaceWaterBody {
    + euSurfaceWaterBodyCode : wiseIdentifier
    + surfaceWaterBodyCategory : WaterBodyCategory
    + naturalAWBHMWB : NaturalAWBHMWB
    + swIntercalibrationType : IntercalibrationType [1..n]
    + swTypeIdentifier : wiseIdentifier
    + surfaceWaterBodyTransboundary : YesNo
    + reservoir : ReservoirType
    + swMixingZonesProportion : PercentageInterval
}

class SWStatus {
    + euSurfaceWaterBodyCode : wiseIdentifier
    \ swEcologicalStatusOrPotentialValue : EcologicalStatus
    \ swChemicalStatusValue : ChemicalStatus
}

class SWPollutant {
    + euSurfaceWaterBodyCode : wiseIdentifier
    + swPollutantCode : Parameter
    + swPollutantCausingFailure : YesNoUnknown
    + swPollutantExceedanceType : EnvironmentalQualityStandard [0..n]
    + swPollutantExceedanceInMixingZone : YesNoUnknownNotApplicable
    
    + swPollutantAssessmentPeriod : range
    + swPollutantAssessmentMethod : AssessmentMethod [1..n]
    + swPollutantAssessmentConfidence : AssessmentConfidence

    + swThresholdIdentifier [1..n]
    + swGroupingIdentifier : wiseIdentifier [0..n]
}

class SWPressureImpact {
    + euSurfaceWaterBodyCode : wiseIdentifier
    + swPressureType : PressureType [0..1]
    + swImpactType : ImpactType  [0..1]
}

class SWHeavilyModifiedWaterBody {
    + euSurfaceWaterBodyCode : wiseIdentifier
    + hmwbPhysicalAlterationType : HMWBPhysicalAlterationType [0..1]
    + hmwbWaterUseType : HMWBWaterUseType [0..1]
}

class SWQualityElement{
    + euSurfaceWaterBodyCode : wiseIdentifier
    + qeCode : QualityElement
    + qeStatusOrPotentialValue : EcologicalStatus
    + qeStatusAssessmentPeriod : range
    + qeStatusAssessmentMethod : AssessmentMethod [1..n]
    + qeStatusAssessmentConfidence : AssessmentConfidence
    + qeClassificationIdentifier : wiseIdentifier [1..n]
    + swGroupingIdentifier : wiseIdentifier [0..n]
}
class SWGrouping{
    + swGroupingIdentifier : wiseIdentifier
    + euSurfaceWaterBodyCode : wiseIdentifier
}

SWHeavilyModifiedWaterBody "0..n" -- "1" SurfaceWaterBody 
SurfaceWaterBody "1" -- "1" SWStatus
SWStatus "1" -- "n" SWQualityElement
SWStatus "1" -- "0..n" SWPressureImpact
SWStatus "1" -- "n" SWPollutant

SWQualityElement .. SWGrouping : swGroupingIdentifier
SWPollutant .. SWGrouping : swGroupingIdentifier

classDef default fill:white,stroke:#000;
classDef forFixing fill:white,stroke:#f00;
classDef otherDataset fill:lightyellow,stroke:#000;
