---
config:
  class:
    hideEmptyMembersBox: true
  layout: dagre
  theme: neutral
---
classDiagram
direction TB

class SurfaceWaterBody {
    + euSurfaceWaterBodyCode : wiseIdentifier
    + surfaceWaterBodyCategory : WaterBodyCategory
    + naturalAWBHMWB : NaturalAWBHMWB
    + surfaceWaterBodyTypeCode : swTypeIdentifier [0..1]
    + surfaceWaterBodyTransboundary : YesNo
    + reservoir : ReservoirType
    + swMixingZonesProportion : PercentageInterval
}

class SurfaceWaterBodyStatus {
    + euSurfaceWaterBodyCode : wiseIdentifier
    \ swEcologicalStatusOrPotentialValue : EcologicalStatus
    \ swChemicalStatusValue : ChemicalStatus
}

class SWPollutant {
    + euSurfaceWaterBodyCode : wiseIdentifier
    + swPollutantCode : Parameter
    + swThresholdIdentifier [1..n]
    + swPollutantCausingFailure : YesNoUnknown
    + swPollutantExceedanceType : EnvironmentalQualityStandard [0..n]
    + swPollutantExceedanceInMixingZone : YesNoUnknownNotApplicable
    
    + swPollutantAssessmentPeriod : range
    + swPollutantAssessmentMethod : AssessmentMethodValue
    + swPollutantAssessmentConfidence : AssessmentConfidenceValue
    + swGroupIdentifier : wiseIdentifier [0..n]
}

class SWPressureImpact {
    + euSurfaceWaterBodyCode : wiseIdentifier
    + swPressureType : PressureType [0..1]
    + swImpactType : ImpactType  [0..1]
}

class SWHighlyModifiedWaterBody {
    + euSurfaceWaterBodyCode : wiseIdentifier
    + hmwbPhysicalAlterationType : HMWBPhysicalAlterationType [0..1]
    + hmwbWaterUseType : HMWBWaterUseType [0..1]
}

class SWQualityElement{
    + euSurfaceWaterBodyCode : wiseIdentifier
    + qeCode : QualityElement
    + qeStatusOrPotentialValue : EcologicalStatus
    + qeStatusAssessmentPeriod : range
    + qeStatusAssessmentMethod : AssessmentMethodValue
    + qeStatusAssessmentConfidence : AssessmentConfidenceValue
    + swGroupIdentifier : wiseIdentifier [0..n]
}
class SWGrouping{
    + swGroupIdentifier : wiseIdentifier
    + euSurfaceWaterBodyCode : wiseIdentifier
}

class SWType ["SWMethodologyDataset::SWType"]:::otherDataset{
+ swTypeIdentifier
}

SWType .. "1..n" SurfaceWaterBody : swTypeIdentifier
SWHighlyModifiedWaterBody "0..n" -- SurfaceWaterBody : {naturalAWBHMWB =! 'natural'}
SurfaceWaterBody -- SurfaceWaterBodyStatus
SurfaceWaterBodyStatus -- "n" SWQualityElement
SurfaceWaterBodyStatus -- "0..n" SWPressureImpact
SurfaceWaterBodyStatus -- "0..n" SWPollutant

SWQualityElement "0..n" .. "0..n" SWGrouping : swGroupIdentifier
SWPollutant "0..n" .. "0..n" SWGrouping : swGroupIdentifier

classDef default fill:white,stroke:#000;
classDef forFixing fill:white,stroke:#f00;
classDef otherDataset fill:lightyellow,stroke:#000;