---
config:
  class:
    hideEmptyMembersBox: true
  layout: dagre
  theme: neutral
---
classDiagram
direction TB

class SWThresholdValue{
+ swThresholdIdentifier: wiseIdentifier
+ parameterCode: Parameter
+ eqsStandardType: StandardType
+ chemicalMatrix: ChemicalMatrixType 

+ thresholdValueRange: range
+ thresholdValueUnit: UnitOfMeasure
+ naturalBackgroundLevelSet: YesNoNotApplicable

«compliance-with-criteria»
+ analyticalMethod: YesNo
+ analyticalMethodBAT: YesNoNotApplicable

«reference»
+ swThresholdReference: referenceCode [0..n]

«for-data-quality-control-purposes»
+ applicableToRW: YesNo
+ applicableToLW: YesNo
+ applicableToTW: YesNo
+ applicableToCW: YesNo
+ applicableToTeW: YesNo
}

class SWPollutant ["SurfaceWaterDataset::SWPollutant"]:::otherDataset{
  + euSurfaceWaterBodyCode
  + swPollutantCode
  + swThresholdIdentifier [1..n]
  + swThresholdExceedance [0..n]
}

SWThresholdValue <.. SWPollutant: swThresholdIdentifier
SWThresholdValue <.. SWPollutant: swThresholdExceedance

classDef default fill:white,stroke:#000;
classDef forFixing fill:white,stroke:#f00;
classDef otherDataset fill:lavender,stroke:#000;